### PR TITLE
Added toolbars for control target

### LINKED ISSUE #125: Toolbar for controls
Since the merge of #90 we need a toolbar to add controls in nicer way, As it is now the placement of controls is dependent on the absolute position in style which will be easily broken if controls are removed,

### PR DESCRIPTION
**Pull request by afogelberg**
Fixes #125

### CODE REVIEW

**Comment by jokd** [comment]
Nice improvement! Works well for me, except for the scaleline is missing. Or has it been deleted?

**Comment by afogelberg** [comment]
@jokd are you using the default map with osm? The scale-line will not show with osm and how the projection is defined. Can you try a map with another projection? We should be able to solve the scale-line problem with #196 .

**Comment by jokd** [comment]
I'm sure you're right. I tested with the default layers with 3857 projection. Won't be able to test other config until next week so discard my previous comment about the scale line since that's another issue.

**Comment by afogelberg** [comment]
Ok to merge then?

**Comment by jokd** [comment]
Its good to go. Well done!

**Comment by afogelberg** [comment]
Great! Thanks for the review

**Pull request merged**
