### PR TITLE
Added datetype to editform

### LINKED ISSUE #338: Add date-field to editform
We should be able to have the type date and in supported browsers (at least Chrome, Edge Firefox v57) show the native datepicker.

### PR DESCRIPTION
**Pull request by jokd**
Fixes #338

### CODE REVIEW

**Comment by markus659** [comment]
Seems to work as expected, a nice addition to Origo. I'm not sure we need the maxLength attribute though? Or what is it purpose in this case?

**Comment by afogelberg** [comment]
@jokd works great in Firefox and Chrome. How about adding todays date as default value? That could help IE users a bit too,

**Comment by markus659** [comment]
Perhaps today's date should auto populate the date field, without any added configuration? Right now you need to specify defaultDate in the config (if I'm doing it right).

**Comment by jokd** [comment]
Now the default behaviour is todays date/time. I you want the field to be empty, set the defaultDate to false.

**Comment by markus659** [comment]
Looks good to me now. I had not noticed the color option previously. Maybe add some information about the color option being added as well when squashing and merging?

**Pull request merged**
