### PR TITLE
Fetch feature info in application/geo+json format

### LINKED ISSUE #1497: WMS GetFeatureInfo application/geo+json option
**Is your feature request related to a problem? Please describe.**
When a WMS don't send FeatureInfo in the format application/json which seams to be the default and only handled in Origo, but have the format application/geo+json it would be nice to be able to specify that the FeatureInfo for this layer should be using application/geo+json

**Describe the solution you'd like**
It should be possible to specify the INFO_FORMAT for the layer like this.
`"infoFormat": "application/geo+json"`

**Describe alternatives you've considered**
The same should be possible for text/plain and text/xml format

### PR DESCRIPTION
**Pull request by johnnyblasta**
Closes #1497 

Example config:
```
  "source": {
    "local": {
      "url": "http://localhost/geoserver/wms"
    },
    "lstY-strandskydd": {
      "url": "https://ext-geodata-lokala.lansstyrelsen.se/arcgis/services/LSTY/lsty_wms_strandskydd/MapServer/WMSServer"
    }
  },
  "layers": [
    {   "name": "0",
            "title": "LST Strandskyddsdispenser",
            "queryable": true,
            "visible": false,
            "type": "WMS",
            "group": "root",
            "source": "lstY-strandskydd",
            "style": "Strandskyddsdispenser",
            "infoFormat": "application/geo+json"
        },

```

### CODE REVIEW

**Comment by Grammostola** [comment]
Hi, I think it looks pretty good, well done. One bit of variability, so far isolated to one arcgis server, is:
```xml
        <Format>application/vnd.esri.wms_raw_xml</Format>
        <Format>application/vnd.esri.wms_featureinfo_xml</Format>
        <Format>application/vnd.ogc.wms_xml</Format>
        <Format>application/geojson</Format>
        <Format>text/xml</Format>
        <Format>text/html</Format>
        <Format>text/plain</Format>
```

whereas your proposed change works well when it looks like  so:

```xml
        <Format>application/vnd.esri.wms_raw_xml</Format>
        <Format>application/vnd.esri.wms_featureinfo_xml</Format>
        <Format>application/vnd.ogc.wms_xml</Format>
        <Format>application/geo+json</Format>
        <Format>text/xml</Format>
        <Format>text/html</Format>
        <Format>text/plain</Format>
```

I shall query whether the singular arcgis server has any relevant local configuration (though I can't quite see how that would be the case). Maybe your proposed change could recognize both of the above variants if both are valid.

**Comment by johnnyblasta** [comment]
> Hi, I think it looks pretty good, well done. One bit of variability, so far isolated to one arcgis server, is:
> 
> ```
>         <Format>application/vnd.esri.wms_raw_xml</Format>
>         <Format>application/vnd.esri.wms_featureinfo_xml</Format>
>         <Format>application/vnd.ogc.wms_xml</Format>
>         <Format>application/geojson</Format>
>         <Format>text/xml</Format>
>         <Format>text/html</Format>
>         <Format>text/plain</Format>
> ```
> 
> whereas your proposed change works well when it looks like so:
> 
> ```
>         <Format>application/vnd.esri.wms_raw_xml</Format>
>         <Format>application/vnd.esri.wms_featureinfo_xml</Format>
>         <Format>application/vnd.ogc.wms_xml</Format>
>         <Format>application/geo+json</Format>
>         <Format>text/xml</Format>
>         <Format>text/html</Format>
>         <Format>text/plain</Format>
> ```
> 
> I shall query whether the singular arcgis server has any relevant local configuration (though I can't quite see how that would be the case). Maybe your proposed change could recognize both of the above variants if both are valid.

These variants are probably exactly the same in the response, but should be requested with the specific format so the code has to be modified a bit.

**Comment by johnnyblasta** [comment]
Made a fix that should handle the varying string for the same format. @Grammostola can you test it on the server?

**Comment by Grammostola** [comment]
Looks good and works well

**Pull request merged**
