### PR TITLE
feature: infowindow for search

### LINKED ISSUE #1228: Search hits could have a choice of infowindow: type
**Is your feature request related to a problem? Please describe.**
Search hits* today display an info popup 'overlay' 

**Describe the solution you'd like**
Search hit infos could be displayed in the infowindow: that the map is set to

**Describe alternatives you've considered**
Search hit infos could be displayed according to a parameter for the search control in index.json

**Additional context**
We are currently working with internal maps employing infowindow:infowindow and have received feedback noting the inconsistency between overlay when clicking search hits and iw:iw when infoclicking/selecting

*employing the standard search control

### PR DESCRIPTION
**Pull request by jokd**
Fixes #1228
Use infowindow for search result if set

### CODE REVIEW

**Comment by steff-o** [comment]
From code inspection it looks like there are still two cases where it is hardcoded to use overlay via the internal _showFeatureInfo_ function instead of calling the function on featureInfo.

I haven't figured out if it not possible to use the featureInfo-version of showFeatureInfo, but if it is possible it should be changed everywhere so it always obeys the setting and the internal showFeatureInfo can be removed.

**Comment by jokd** [comment]
> From code inspection it looks like there are still two cases where it is hardcoded to use overlay via the internal _showFeatureInfo_ function instead of calling the function on featureInfo.
> 
> I haven't figured out if it not possible to use the featureInfo-version of showFeatureInfo, but if it is possible it should be changed everywhere so it always obeys the setting and the internal showFeatureInfo can be removed.

In that case the featureInfo.showFeatureinfo has to be changed to allow features that are not in a layer. Maybe that can be adressed in another issue?

**Comment by steff-o** [comment]
Ok, that was what I expected, just didn't have time too dig into the details but I remembered that there was something special about how search (mis)used featureInfo.render().

If it is a larger rewrite we could probably settle for this PR at the moment, but it would be nice fix all cases to avoid confusion.

**Comment by jokd** [comment]
> Ok, that was what I expected, just didn't have time too dig into the details but I remembered that there was something special about how search (mis)used featureInfo.render().
> 
> If it is a larger rewrite we could probably settle for this PR at the moment, but it would be nice fix all cases to avoid confusion.

I think it's quite a rewrite to fix the other cases so I suggest we fix that in another issue. 
So if it's ok it would be nice if this was merged.

**Review by steff-o — APPROVED** [review]
LGTM. 

But...
The case in line 147 does not make any sense. The newly created feature does not have any attributes, so infowindow will be empty. But that was also the case before this PR. Maybe the intention was that all attributes should be read from search response? In that case it would make sense to point out the layer to get the correct attribute formatting. Well, at least it will obey the "infoWindow"-setting without breaking anything.

Overall I don't think that the documentation is describing the five cases correctly. For instance, case 2 seems impossible to achieve.  #1420 would be welcome.

**Comment by jokd** [comment]
> LGTM.
> 
> But... The case in line 147 does not make any sense. The newly created feature does not have any attributes, so infowindow will be empty. But that was also the case before this PR. Maybe the intention was that all attributes should be read from search response? In that case it would make sense to point out the layer to get the correct attribute formatting. Well, at least it will obey the "infoWindow"-setting without breaking anything.
> 
> Overall I don't think that the documentation is describing the five cases correctly. For instance, case 2 seems impossible to achieve. #1420 would be welcome.

Yeah it is a bit messy but this PR aims to use the configured infowindow where possible. Further improvements can be addressed and solved in another PR, such as issue #1420

**Pull request merged**
