### PR TITLE
Removed touchend

### PR DESCRIPTION
**Pull request by afogelberg**
This PR solves #80 and #81 . Can we merge this?

### CODE REVIEW

**Comment by markus659** [comment]
There is one touchend remaining here: https://github.com/origo-map/origo/blob/remove-touchend/src/transactionhandler.js#L155

**Comment by afogelberg** [comment]
Thanks for the review @markus659 . I removed the remaing touchend.

**Comment by markus659** [comment]
Seems to work well otherwise (tested on tablet and phone). I will approve the changes.

**Comment by afogelberg** [comment]
@markus659 Can you verify that it also solves #80 ?

**Comment by markus659** [comment]
Yes, it does solve the problem described in #80.

**Pull request merged**
