### PR TITLE
Fixed build script

### LINKED ISSUE #584: Unable to deploy ./build without modification due to invalid js/origo.js
When deploying the ./build folder on a web server it wont work since the js/origo.js is invalid. The minified js/origo.min.js will work though if you manually make the switch.

### PR DESCRIPTION
**Pull request by jokd**
Fixes #584

### CODE REVIEW

**Comment by tonnyandersson** [comment]
Works fine! But is it really necessary to include the build/js/origo.js file in this PR? Not saying that it shouldn't be included, but historically, we've only updated build files before making new releases. Sort of.

**Comment by jokd** [comment]
Well true, but this way you can dl master and it'll actually work out of the box.

**Comment by jokd** [comment]
But maybe we should make this fix 2.0.2 unless we rerelease 2.0.1

**Comment by tonnyandersson** [comment]
New features has been added since 2.0.1, so I guess it would be more correct to make a 2.1.0 release. But that feels like too big a leap.

**Comment by jokd** [comment]
Removed origo.js and merged

**Pull request merged**
