### PR TITLE
Fixes print bug when height>width

### LINKED ISSUE #784: Print issues when width>height
When using custom format the resulting pdf is distorted if the width is greater than the height.
image

### PR DESCRIPTION
**Pull request by jokd**
Fixes #784
Further improvement would be to remove the portrait/landscape orientation buttons when setting custom sizes since they are confusing.

### CODE REVIEW

**Comment by tonnyandersson** [comment]
@jokd I agree that the portrait/landscape buttons should be removed OR be connected to the heigth/width sliders so that p/l mode changes automatically when changing h/w, and vice versa. The latter would require more work, though, and may not be particularly useful. So I vote for hiding p/l when a custom size is set.

I think, however, that it should be done in this PR. No point in waiting. Confusing AF, right now.

**Comment by jokd** [comment]
This fixes the bug that creates corrupt pdfs. Removing the toolbar can be added as an enhancement in the #785 issue. Is that ok?

**Comment by tonnyandersson** [comment]
I guess I can live with that.

**Comment by tonnyandersson** [comment]
Works well, PDF:s are no longer distorted.

**Pull request merged**
