### PR TITLE
Fix for sidebar

### LINKED ISSUE #531: Sidebar not working in 2.0
Featureinfo in sidebar is not working since 2.0 release

### PR DESCRIPTION
**Pull request by jokd**
Fixes #531

### CODE REVIEW

**Comment by tonnyandersson** [comment]
@jokd Works fine. But perhaps the styling should be updated?

**Comment by jokd** [comment]
Oh, forgot to push that. Will do.

**Comment by jokd** [comment]
@tonnyandersson Please have another look

**Comment by tonnyandersson** [comment]
Looks good!

**Pull request merged**
