### PR TITLE
feature: draw as core control

### LINKED ISSUE #1610: Adding draw to core
**Is your feature request related to a problem? Please describe.**
The draw plugin is widely used and should be in the origo core. Adding it won't be many kB extra to the build and it will be the first step in solving #1609.

### PR DESCRIPTION
**Pull request by jokd**
Fixes #1610 
Major rewrite of the draw plugin to make it a core control. Also the measure control has some new functionality.
Will update this post with the changes made and how to configure the control soon.

### CODE REVIEW

**Comment by jokd** [comment]
It is now possible to add measures to the drawed objects:
image

And the measure control objects can be modified:
image

**Comment by Grammostola** [comment]
With the given configuration, except `queryable: true` and `showSaveButton: false` the drawn features and their given popup texts transferred via a saved mapstate and were printable. When changing the DPI in the print pane however the shapes change form/size. related to it needing to be a vector-layer as per pr 64 of the draw plugin (that you previously included; it isn't immediately apparent where the layer is coming from here). 

I also experienced troubles with the two line types,
``` 
 function stringToRgba(colorString, opacity) {
    if (colorString.toLowerCase().startsWith('rgba(')) { return colorString; }
```
Thinks that colorString is undefined

Anyway I think the info popup definition of drawn objects is a great idea and I like where this PR is headed

**Comment by johnnyblasta** [comment]
The font-weight is a bit much in my opinion:
image

**Comment by jokd** [comment]
Now I have hopfully fixed the printing issues. The measure labels won't scale though since they are hard coded. But maybe we can live with that? 

Changed the label class:
image

**Comment by johnnyblasta** [comment]
When a buffer is used in the measure control the print throws a error.

**Comment by jokd** [comment]
> When a buffer is used in the measure control the print throws a error.

Pushed a fix for this as well as label scaling

**Comment by Grammostola** [comment]
My prior complaints are now void. I can't seem to make measurements saveStateToServer however.

**Comment by jokd** [comment]
> My prior complaints are now void. I can't seem to make measurements saveStateToServer however.

Forgot about measure in mapstate, and I haven't been able to test against old mapstates but seems to work with newly created.

**Comment by filleg** [comment]
Some really nice improvements. Tested some measurements both in measure and in draw. The labels of measurements seems to be off when changing to a different projection code than web mercator. Verified by exporting the drawing and measuered it in QGIS.

**Comment by jokd** [comment]
> Some really nice improvements. Tested some measurements both in measure and in draw. The labels of measurements seems to be off when changing to a different projection code than web mercator. Verified by exporting the drawing and measuered it in QGIS.

Is it the same as this issue: https://github.com/origo-map/origo/issues/1617 ?

**Comment by filleg** [comment]
No, the difference is a bit bigger. Otherwise I probably wouldn't have noticed :)

image

**Comment by johnnyblasta** [comment]
Looks like it measures correct now when I tested.
Perhaps ready to merge now?

**Comment by jokd** [comment]
@Grammostola @filleg 
Can you have another look?

**Comment by filleg** [comment]
Looks good now.

**Comment by steff-o** [comment]
@johnnyblasta, I don't think it's ready to merge quite yet. I have some issues that I will post soon.

**Comment by steff-o** [comment]
As promised, here are my observations. I have not found anything that actually is blocking a merge, but some things that would be nice to have fixed at some point.

First of all, great job. It has a great look and feel and some really nice features.

__Here are some stuff that I think should be fixed as soon as possible:__
- The exported filename should default to the name of the draw layer. As on now, the name is "export" when saved from menu and layer dialog. When saved from TOC it is "Ritlager".
- Buttons for attributes and delete should be greyed out when no feature is selected
- It is a bit unclear what the style selector changes. The idea to switch between currect object and "default" is good, but I would like a change in title when no feature is selected to indicate that it will be the new "default".
- I would prefer if there was an actual default symbol. Right now the next drawn object will get the same symbol as the last selected.
- I think its a bit unclear that the export button in the menu only exports the active layer. Not sure what to do about it. Export all? Remove it? Maybe its clearer if the export gets the name of the layer?
- The attribute name in the geojson file is "style". Not really anything crucial about it, but it could possibly collide with a user attribute name, especially if it will become possible to import arbitrary files. Maybe it should be named something more unlikely like "__origo_style"
- I don't see the logic in having all other tools in the left menu when draw is the same type of tool as measure and edit where only one can be active at a time. If moving to the left menu the close button can be removed. BTW, the measure tools should also be in the bottom toolbar.
- It is not obvious that the only way to abort a draw tool (get back to select) is to click the same tool again (or draw an object and delete it). Maybe should have a select tool.

__Code review__
As the diff is a couple of thousand of lines of code I have not code reviewed much. But when browsing through the code if saw that the drawhandler dispatches events on behalf of the draw component. Looks a bit backwards to me when the purpose is to communicate with the draw component and possibly makes it harder to follow the flow. In my opinion it would be handled by a direct call to the draw component and let the component dispatch its own events, or having draw component listen to events from the drawhandler.

__Nice to haves__
Here are some features that I would like to have, but is probably best suited as later additions:
- More custom attributes
- Automatically store drawings in localstorage
- Import of arbitrary geojson files for editing. If they have the style-attribute it will be used.

**Comment by jokd** [comment]
Pushed a commit where:
Rewrote drawHandler as a component
Changed export names
Grayed out icons

As for the stylewindow, a reset button can be useful. The idea of not having a default style is to be able to reuse a certain (not default) style without resetting every setting, therefor you inherit last objects style. But a button to reset it makes sense.

The export button maybe is redundant since you also can export from the legend?

I plan to make it configurable whether to have the button i the legend and/or in the left menu. Just like the print control.

**Comment by steff-o** [comment]
@jokd I have to break it to you but the fix for greyed out attributes button does not work the first time draw is activated (it works for delete). All other changes looks good.

**Comment by johnnyblasta** [comment]
@jokd might be nice to have a way in config to set that the draw tool should be active on start.
`"initialState": "active"`
Default value should be not active.

**Comment by jokd** [comment]
Now there's an isActive-setting that defaults to false if you want to activate the control at start.
Also a button to import geojson layer:
image
Supports edits and sharemap as well.

**Comment by johnnyblasta** [comment]
I'm not getting the specified exra draw tools. @jokd 

My config:
```
 {
    "name": "draw",
    "options" : {
      "buttonText": "Rita", 
      "drawTools": { 
         "Polygon": ["freehand", "box"],
         "LineString": ["freehand"]
      },
```

**Comment by jokd** [comment]
> I'm not getting the specified exra draw tools. @jokd
> 
> My config:
> 
> ```
>  {
>     "name": "draw",
>     "options" : {
>       "buttonText": "Rita", 
>       "drawTools": { 
>          "Polygon": ["freehand", "box"],
>          "LineString": ["freehand"]
>       },
> ```

Now it should work. I moved the event handling and forgot about the extra tools.

**Comment by jokd** [comment]
Anyone dare to approve this or are there more stuff to fix?

**Comment by asemoller** [comment]
I've some inputs!

1. I'm not sure if the icon for attributes should be the same as for the mapmenu, it's a bit confusing. What about [textsms](https://fonts.google.com/icons?selected=Material%20Icons%3Atextsms%3A), [textfield](https://fonts.google.com/icons?selected=Material%20Icons%3Atext_fields%3A) or something similar?
2. When you add a new layer, it becomes active and gets the default name. It's not obvious that the layer on top is the new one. What about adding a number suffix to the new layer (Ritlager (1)) or just not making the new layer active?

I really like this new feature!

**Comment by asemoller** [comment]
> Auto activating a new layer makes sense to me but I guess it could be done the other way as well.

I agree, it makes sense! A suffix makes it more obvious that a new layer has been created and I think that's enough. Well done! (haven't tried it yet but it looks good.) 😃

**Comment by Grammostola** [comment]
Drawn features incl measurement labels get thinner anew when -> 300dpi in the print preview (measure lines from the measure tool and their labels are ok)

**Comment by jokd** [comment]
@Grammostola Scaling should work now

**Comment by Grammostola** [comment]
Cheers for the quick attention, drawn features now rescale properly when 300dpi in the print preview, however measure lines do not and upon exiting the print preview they turn into red non-dashed lines with no label.

**Comment by jokd** [comment]
> Cheers for the quick attention, drawn features now rescale properly when 300dpi in the print preview, however measure lines do not and upon exiting the print preview they turn into red non-dashed lines with no label.

Yeah there was problem with default style as well. The resize function can't handle style functions so the function itself must do the scaling.

**Comment by jokd** [comment]
...thinking a bit more, perhaps the default style function should be the same as for draw. But that's another issue.

**Comment by jokd** [comment]
> Looks fixed : ) Depending on how things progress I'll endeavour to test some more tomorrow but currently I've no further things to note.

Please do, would be great to merge before release

**Comment by jokd** [comment]
@Grammostola OK to merge this? Keen to make the release and this is the last piece in the puzzle

**Comment by Grammostola** [comment]
I detected no other anomalies when I tested yesterday but haven't had the time to check today (we are in the process of a software update). As far as I can tell at the moment it looks good but further testing wouldn't hurt. I don't expect to be able to do that before lunch however. (I still have some documentation stuff to do too which would rhyme well with the release)

**Comment by johnnyblasta** [comment]
@jokd I'll have a wack at testing it now to see if I find anything more.

**Review by johnnyblasta — APPROVED** [review]
This gets a big thumbs up from me, good work!
Happy easter!

**Comment by Grammostola** [comment]
Indeed, I've tested some more (primarily around printing and sharing) which seemed to work : ) Well done.
(One peripheral thing I noted is that drawn features from the current plugin version do not seem to retain their style when opened with this version. There are various ways around that, including communication, as it may not feasibly be within the scope of this pr). Happy easter holidays!

**Comment by MattiasSp** [comment]
What a fantastic job on this PR @jokd and big applause to everyone giving constructive feedback 👏👏👏

This feature alone warrants a swift upgrade to 2.7! Cheers! 😄

**Pull request merged**
