### PR TITLE
Create a print legend for AGS_* layers

### PR DESCRIPTION
**Pull request by sweco-sedalh**
Fetches information from ArcGIS MapServer for the legend, similarly to how to is done for WMS legends support JSON legends.

Also detects WMS layers that are actually MapServer layers and uses the same code for those, since MapServer does not provide JSON data for WMS legends.

Closes: #1525

### CODE REVIEW

**Comment by jokd** [comment]
@Grammostola I am uable to test this but if it's good then I suggest you merge it.

**Comment by Grammostola** [comment]
There's a crash when the print preview is summoned with a wfs theme layer visible in the map:

```
print-legend.js:122 
        
       Uncaught (in promise) TypeError: children.join is not a function
    at getTitleWithChildren (print-legend.js:122:22)
    at getStyleContent (print-legend.js:180:12)
    at Object.render (print-legend.js:242:19)
    at eval (print-legend.js:275:95)
    at async Object.render (print-legend.js:275:27)
    at async Object.render (print-legend.js:282:15)
    at async Object.render (print-legend.js:311:17)
    at async Object.addPrintControls (print-map.js:93:76)
    at async Object.onRender (print-component.js:578:7)
```
wfs theme layer defined like so
```json
{
  "name": "sokvyx_transport_cykelleder_cykelkarta",
  "title": "Cykelleder",
  "group": "root",
  "queryable": true,
  "type": "WFS",
  "visible": false,
  "searchable": true,
  "source": "etuna",
  "style": "cykelledtema"
},

    "cykelledtema":  [
      [
        {
          "stroke": {
            "color": "rgba(115,200,176,0.7)",
            "width": 2
          },
          "filter": "[title] == 'Lejonrundan'",
          "label": "Lejonrundan"
        }
      ],
      [
        {
          "stroke": {
            "color": "rgba(210,89,100,0.7)",
            "width": 2
          },
          "filter": "[title] == 'Näckrosleden'",
          "label": "Näckrosleden"
        }
      ]
    ],

```

**Comment by sweco-sedalh** [comment]
@Grammostola The bug has been fixed

**Comment by Grammostola** [comment]
@tonnyandersson Yep, appears fixed. I've tested the PR further with different variations of theme and non-theme WMS and AGS-map layers, including WMS layers from an AGS. It also adds the icon for a non-theme AGS map layer without a style, though normally the layer would include a style for the map legend. AGS theme layers can afaik at most have a pregenerated image as a map legend today, as mentioned in the issue this is a separate issue, the pregenerated image will take precedence over the functionality in this PR that finds and generates the theme legend. Said functionality will take precedence over a style that defined a getlegendgraphic call. (So WMS layers from an AGS can have a getlegendgraphic theme legend in the map and a better looking legend in print).

**Pull request merged**
