### PR TITLE
Make getLayers aware of layers in groups

### LINKED ISSUE #1197: WMS GetFeatureInfo not working for layers in a group
**Describe the bug**
WMS GetFeatureInfo not working for layers in a group.

**To Reproduce**
Make a group and add a queryable WMS layer in it. (Geoserver layer used for test)

Editor example can be used for fast testing, change editor_polygon layer type from WFS to WMS and add it in a group.
Close editor and try infocklicking results in error.

**Expected behavior**
Should work the same as a standalone WMS layer featureinfo click.

**Screenshot devtools**
probs_wms_grouplayer

### PR DESCRIPTION
**Pull request by jokd**
Fixes #1197 
The getLayers function in viewer will instead of returning a layerGroup return the individual layers in the group. I have not thoroughly tested how this affect other tools but I am not aware of any that uses the getLayers in that way.

### CODE REVIEW

**Comment by Grammostola** [comment]
Hi, I'll check how this affects https://github.com/origo-map/origo/tree/share-selection-in-grouplayer-fix (a changed getLayer() ) before initiating a PR for it. It's one of two planned for #969

**Comment by tonnyandersson** [comment]
I think you need to make two different getLayer functions, or at least pass an argument that states if groups should be split open on not. Different contexts need different results, as I'm sure you've noticed.

**Comment by jokd** [comment]
Tough one. We have the getGroupLayers function so I think it makes sense not to include grouplayers in getLayers but thats not how its been used and will probably take some effort to get things straight.

**Comment by tonnyandersson** [comment]
Actually, it does make sense to include group layers in getLayers when the layers in the group need to be treated as one, e.g. for the legend, some permalink stuff (visible/not visible) etc. But when feature access is crucial, the grouped layers must be treated as separate layers.

I think an argument would takes us quite far, like:

```javascript
const getLayers = function getLayers(explodeGroup) {
  const arr = [];
  const layerArray = map.getLayers().getArray();
  layerArray.forEach((element) => {
    if (element.get('type') === 'GROUP' && explodeGroup) {
      element.getLayers().getArray().forEach((layerInGroup) => {
        arr.push(layerInGroup);
      });
    } else {
      arr.push(element);
    }
  });
  return arr;
}
```

**Comment by jokd** [comment]
Well that might work but some functions will need to be rewritten. But on the other hand we will gain some functionality. Make layers in group searchable for instance.

**Comment by jokd** [comment]
However! the getLayer function will probably want both the group and the individual layers since it is filtering on layer name.

**Comment by tonnyandersson** [comment]
Depends on the situation, I'd say.

**Comment by Grammostola** [comment]
I'm merely a little lost so will venture : is getLayer ever expected to return a group layer object? One of two problems described in 969 was that getLayer() filtered the top layer of the array, with potential layer groups when groups inside of layer groups were wanted. If Tonny's suggestion above is implemented then my tweak of getLayer isn't necessary and getLayer can merely summon getLayers with a truthy value for expose group contents.  Unless getLayer is somewhere expected to return a group layer object.

(I suppose there's no point to layers in group layers in group layers)

**Comment by jokd** [comment]
getLayer is used for both group layers and the individual layers so your tweak is not unnecessary, unless we make getLayers return both group layers its contained layers

**Comment by tonnyandersson** [comment]
I think the main changes should be made to `getLayers`, since that's the "base" function for getting layers. `getLayer` uses it, other functions goes straight for `getLayers`, and so on.

But then there's a few bad guys going straight for the `map.getLayers()` function...

**Comment by jokd** [comment]
Yeah but getLayer must be able to find both group layers and the layers it consists of so somehow must be rewritten depending on how we handle getLayers

**Comment by tonnyandersson** [comment]
Yeah, perhaps by passing the explode/expose argument when necessary?

```javascript
const getLayer = (layerName, explodeGroups) => getLayers(explodeGroups).filter(layer => layer.get('name') === layerName)[0];
```

**Comment by jokd** [comment]
You are not always aware whether it is a group layer or not you are looking for so it needs 'em all

**Comment by tonnyandersson** [comment]
Perhaps you need to make yourself aware. Since group layers and regular layers can't be treated the same way in any given situation (not the same methods or properties etc.), you can't just get them all at once and expect to be able to process them the same way. You would have to implement all kinds of checks and safeguards every time you call `getLayers()`.

Take a look at your latest commit, for example. There you're getting all layers - regular layers, group layers, grouped layers - in a mixed bag, and it messes the legend up gloriously.

**Comment by jokd** [comment]
I am talking about getLayer

**Comment by tonnyandersson** [comment]
Oh, of course. That would work. As long as you don't have group layers and grouped layers with the same name, but that's a minor issue. But I guess you'd still have to check for group layers in `getLayers` and possibly handle them differently depending on the situation.

**Comment by jokd** [comment]
Maybe @Grammostola idea is the way to go after all, leave getLayers as is and let getLayer find layers contained in a group as well as ordinary layers.

**Comment by Grammostola** [comment]
If getFeatureInfo uses getLayer (for this issue) and if everything calling getLayer wants to find a layer obj my suggestion or I guess Tonny's explode above; if there are pieces of Origo that are calling getLayer and expecting a groupLayer obj or groupLayer obj / layer obj then it can't as it is, If I've understood things correctly.

**Comment by jokd** [comment]
@Grammostola I would say most (all?) cases are covered in your solution; first if there's a layer with the name it is returned, if not, check the group layers if any of them contain the requested layer and in that case return that layer, not the group layer.
Not touching the getLayers function is probably wise after all.
I pushed your suggestion which partly fixes #969 as well (haven't tested the __-layers)

**Comment by tonnyandersson** [comment]
Works in most cases. Sharing a map with group layer objects selected still doesn't work with the release test config, but that's because of layer names and __-layers.

**Comment by Grammostola** [comment]
Alright : ) No, __ layers are special and there'll be some cheap trickery in the branch I made for that shortly.

**Pull request merged**
