### PR TITLE
Clear tooltip on deactivate

### LINKED ISSUE #1130: Help tooltip on measure not erased on disable
**Describe the bug**
The help tooltip on measure is not erased when disabling the tool.

**To Reproduce**
1. Activate tool and measure something
2. Deactivate the tool
3. The help text is left on the map at last position of cursor.

**Expected behavior**

**Screenshots**
image

### PR DESCRIPTION
**Pull request by johnnyblasta**
Fixes #1130

### CODE REVIEW

**Comment by tonnyandersson** [comment]
This fix results in an error.

image

Steps to reproduce:

1. Activate the measure control by clicking the measure button
2. Start measuring by clicking in the map
3. Deactivate the measure control by clicking the measure button _without finishing the measuring first_

**Comment by johnnyblasta** [comment]
Updated to avoid error when tool is still in measuring mode.

**Comment by tonnyandersson** [comment]
Seems to fix the issue at hand. However, there's still a problem with "ghost labels". Not _directly_ related to this issue, though.

measure

**Comment by johnnyblasta** [comment]
> Seems to fix the issue at hand. However, there's still a problem with "ghost labels". Not _directly_ related to this issue, though.
> 
Yes, I saw that too, but chose to ignore it since it wasn't directly the issue.

**Comment by tonnyandersson** [comment]
I'll approve this then and open/reopen an issue for the labels.

**Review by tonnyandersson — APPROVED** [review]

**Pull request merged**
