### PR TITLE
Multiselection fixes

### LINKED ISSUE #1027: Minor adjustments to make Origo work with the Multiselection plugin
The multiselection plugin requires some changes to Origo

### PR DESCRIPTION
**Pull request by jokd**
Adjustments to make Origo work with the multiselection plugin
Fixes #1027

### CODE REVIEW

**Comment by tonnyandersson** [comment]
There are multiple linter errors in the multiselect.js file.

**Comment by jokd** [comment]
That file shouldn’t have been included so don’t bother, I will remove it.

**Comment by jokd** [comment]
@tonnyandersson Now its way gone

**Comment by tonnyandersson** [comment]
@jokd Took it for a spin, nothing seems broken. I'll approve.

**Review by tonnyandersson — APPROVED** [review]

**Pull request merged**
