### PR TITLE
Adds Progressbar

### LINKED ISSUE #402: Add Progressbar
I would like to add a progress bar to Origo. 
For each layer the progress bar displays the loading time. 
This feature would prompt the user for patience when loading time is an issue.

### PR DESCRIPTION
**Pull request by daRasmussen**
Fixes #402

### CODE REVIEW

**Comment by jokd** [comment]
I think this is really nice and it works well.
How about showing an empty bar when loading is initiated? Now you just see the bar when the first tile has been loaded and sometimes that can take a while.
Would it be possible to include vector sources?
Theres a console.log in progressbar.js that can be removed and also a change in examples/editor.json

**Comment by afogelberg** [comment]
This is a nice addition @daRasmussen, but please look on how our other controls are written and try to follow the same pattern.

**Comment by daRasmussen** [comment]
@jokd @afogelberg I appreciate your comments and insights. Feel free to checkout the [update](https://github.com/origo-map/origo/pull/462/commits/d69b7dd2272fdfbe3202a706f0974128524d896c).

**Comment by jokd** [comment]
Care to rewrite this for Origo 2? I really like the control and it would be a nice addition to Origo.
How about showing an empty bar when loading is initiated? Now you just see the bar when the first tile has been loaded and sometimes that can take a while.
Would it be possible to include vector sources?

**Comment by daRasmussen** [comment]
@jokd sure thing

**Comment by daRasmussen** [comment]
Closing this due to its outdated state see PR #603 for more info.

**Pull request closed without merging**
