### PR TITLE
Fixed editor image upload bug

### LINKED ISSUE #1126: Editor - image handling problems
**Describe the bug**
The editor have problems handling images.

Images can be uploaded and saved, but not deleted. 
After using the form to delete images and then reopen the object, images are still there.

If using form with two image fields:
Uploading image´s to both fields and clicking "OK", only one image is saved, but in both fields.
Uploading image to only one field and clicking "OK" error message appears in console.
> origo.min.js:483 Uncaught TypeError: Failed to execute 'readAsArrayBuffer' on 'FileReader': parameter 1 is not of type 'Blob'.
>     at origo.min.js:483
>     at FileReader.document.getElementById.addEventListener.e.forEach.n.onload (origo.min.js:483)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version Version 87.0.4280.141

**Additional context**
Testing using origo master from 2021-01-21, 17:00

### PR DESCRIPTION
**Pull request by tonnyandersson**
Fixes #1126. I think.

### CODE REVIEW

**Comment by Flodkvist** [comment]
Works good when using one image field.

Problems with multiple imagefields are still present.

**Comment by tonnyandersson** [comment]
@Flodkvist Please try it now. Note that I wasn't able to test _saving_ images since I don't have the appropriate backend for it.

**Comment by Flodkvist** [comment]
@tonnyandersson Works great!

**Comment by jokd** [comment]
Looks like we can merge this?

**Comment by tonnyandersson** [comment]
@jokd Yes, just waiting for an approval.

**Review by jokd — APPROVED** [review]

**Pull request merged**
