### PR TITLE
Added number and hidden as input types

### PR DESCRIPTION
**Pull request by jokd**
This PR is another way to solve #552 and introduces the number and hidden input types for the editor form. 
Along the hidden type it would be nice to introduce some default values/functions to populate the field. Eg todays date.

### CODE REVIEW

**Comment by tonnyandersson** [comment]
@jokd Shouldn't the "hidden" attribute be hidden in the featureinfo popup as well?

image

image

**Comment by jokd** [comment]
Well, not sure about that. I guess it depends, perhaps make it configurable? Or we add the "readonly" property for input types that should be autopopulated and shown and keep the hidden field always hidden?

**Comment by tonnyandersson** [comment]
I just don't like the inconsistency in having something invisible in one place and visible in another. Perhaps the latter then, with "readonly" as a slightly greyed out, non-editable field and "hidden" as really hidden?

**Comment by jokd** [comment]
@tonnyandersson Now its totally hidden, I hope

**Comment by tonnyandersson** [comment]
@jokd Resolve the conflicts and I think we're good to go.

And please provide a simple config example next time. Doesn't have to be a complete config file, just a few lines showing the relevant settings. Guessing takes time... :)

**Comment by jokd** [comment]
@tonnyandersson Sure, sorry about that

**Pull request merged**
