### PR TITLE
Editform overhaul

### LINKED ISSUE #1143: Validate editform does not work as expected
Validate editform does not work as espected due to searchList

_Originally posted by @mulfvik in https://github.com/origo-map/origo/issues/1138#issuecomment-768499963_

### PR DESCRIPTION
**Pull request by mulfvik**
Fixes #1143 and some other bugs in editor

### CODE REVIEW

**Comment by mulfvik** [comment]
During tests I'm not able to do any kind of updates or delete, only inserts (this is also when only using string types in PostGIS):
Geoserver 2.20.2, 
PostgreSQL 14.1,
PostGIS 3.2

Getting back:
`<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows http://localhost:8080/geoserver/schemas/ows/1.0.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>java.lang.NullPointerException</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>`

**Comment by mulfvik** [comment]
Above got sorted by setting "workspace", or rather namespace, to "http://localhost:8080/geoserver"

**Comment by mulfvik** [comment]
Can not reproduce issue #1296 at this point

**Comment by mulfvik** [comment]
[Commit 5d3b786](https://github.com/origo-map/origo/pull/1447/commits/5d3b786e662d612bfd0037393a96f7ff772baf6e)
When defining workspace setting in source (featureNS) as an URI it produces an error due to the workspace setting fallback on featurePrefix option. If prefix setting is defined this doesnt happen. 
`Failed to execute 'setAttributeNS' on 'Element': The qualified name provided ('xmlns:https://karta.haninge.se/devmaps/origo_editor_typetest/ows/Geoinfo') contains multiple colons.`
Removed the workspace fallback (cant find any use case of it) with this commit but it could be an error message instead that describes the necessity of prefix setting.
[https://openlayers.org/en/latest/apidoc/module-ol_format_WFS-WFS.html#writeTransaction](https://openlayers.org/en/latest/apidoc/module-ol_format_WFS-WFS.html#writeTransaction )

**Comment by mulfvik** [comment]
[Commit e19453d](https://github.com/origo-map/origo/pull/1447/commits/e19453dba8312ddbc679816af5817659ac738cdd)
In some enviroments i get this below, this is a fix for that.
image

**Comment by jokd** [comment]
@mulfvik Is this good to go?

**Comment by mulfvik** [comment]
@jokd Yes, it's good to go... for now :)

Besides that QGIS-server still does'nt accept empty inserts on integer, decimal, dates and times (a wild guess is that it's not quite compatible with wfs-t version 1.1.0) its been validated on:

Geoserver 2.20.2,
PostgreSQL 14.1,
PostGIS 3.2

PC and Samsung:
Chrome
Firefox

**Review by jokd — APPROVED** [review]

**Pull request merged**
