### PR TITLE
Search function for legend control

### LINKED ISSUE #1330: Legend search
**Is your feature request related to a problem? Please describe.**
With a legend (or layer list) that contains many layers, it can be difficult for the user to find the right layer in the list. It should be possible to search for layers (and groups?) in the legend. 

**Describe the solution you'd like**
One solution is to have a search function in the legend. Another solution could be to improve the search control so that it also includes layers which, when clicked in the results list, make them visible in the map.

### PR DESCRIPTION
**Pull request by johnnyblasta**
Closes #1330 

Introduces 3 new configurations options:
```
{
  "name": "legend",
  "options": {
      "searchLayersControl": true,
      "searchLayersMinLength": 2,
      "searchLayersLimit": 10
  }
}
```

### CODE REVIEW

**Comment by jokd** [comment]
I get a list but nothing seems to happen when I click one of the results?
Shall layers not visible in the legend be excluded from search results? When searching origo in default config i get both Origokommuner and origo-mask (who belongs to group 'none').

**Comment by johnnyblasta** [comment]
> I get a list but nothing seems to happen when I click one of the results? Shall layers not visible in the legend be excluded from search results? When searching origo in default config i get both Origokommuner and origo-mask (who belongs to group 'none').

If layer is already visible nothing happens when clicked. Should it be toggled?
As it is now it searches on layer name and title, should it also search on abstract?
What is the opinion on whether certain layers should be excluded?
The search function makes most sense when the legend contains a lot of layers in multiple groups.

**Comment by jokd** [comment]
I think I expected a toggle or zoom-to-layer-in legend-function but maybe just turning on is enough. Or if it in the search results was indicated whether its turned on or off, then a toggle function would be the best. Otherwise you must find the layer in the legend to be able to turn it off if that's what you want....
Also inclulde abstract is not a bad idea, like a light metadata search.
I think that layers that are not visible in the legend should be excluded.

**Comment by johnnyblasta** [comment]
Added the possibility to search on abstract for the layer and make it configurable, default is only to search in name and title. 
Excluded layers that belongs to group none in the search.

```
    {
      "name": "legend",
      "options": {
        "searchLayersControl": true,
        "searchLayersMinLength": 2,
        "searchLayersLimit": 10,
        "searchLayersParameters": ["name", "title", "abstract"],
      }
    }
```

**Comment by johnnyblasta** [comment]
I've had plans to include a zoom-to-layer-in legend-function but haven't had time to do it so thought it might be best to release this now and improve it later.

**Review by jokd — APPROVED** [review]
I think this is good to merge

**Pull request merged**
