### PR TITLE
Resizable on o-modal class

### PR DESCRIPTION
**Pull request by mulfvik**

### CODE REVIEW

**Comment by jokd** [comment]
Should this somehow be optional? Also there are no support in IE/Edge, do we bother?

**Comment by mulfvik** [comment]
Would it be good to have for #777 ? Else no bother

**Comment by jokd** [comment]
In that case it could be inline when creating the modal and the content is an iframe?
Its a nice feature indeed.

**Comment by jokd** [comment]
@mulfvik Added your solution inline when creating the modal with iframe. Perhaps thats the only situation where you want to be able to resize the modal?

**Pull request closed without merging**
