### PR TITLE
Fix map name parsing in permalink store getState() function

### LINKED ISSUE #2014: Change permalinkstore state.map split param
Sometimes there can be more than one dot in the path to the configuration file so it would be a better solution to split getMapName() on ".json" instead of on "." for state.map in permalinkstore.

### PR DESCRIPTION
**Pull request by mulfvik**
Fixes #2014

### CODE REVIEW

**Comment by tonnyandersson** [comment]
Is it 100% certain that the map name contains '.json'? What if someone decides to use .geojson or .txt or something?

Perhaps it would be safer to split at the last occurence of '.'?

Not asking you to change this, just raising the question.

**Comment by mulfvik** [comment]
Sure, why not

**Comment by huggla** [comment]
I don't think this works with inline configuration. Related to this issue https://github.com/origo-map/origo/issues/1927

**Comment by mulfvik** [comment]
> I don't think this works with inline configuration. Related to this issue #1927
> 
> Nevermind, I think I mixed things up. This is reading from mapstate-json not config-json, right?

Is there (still?) an issue?

**Comment by huggla** [comment]
If there is a problem after https://github.com/origo-map/origo/issues/1927 has been fixed then I'll open a new issue. I think this should be ok to merge.

**Review by tonnyandersson — APPROVED** [review]

**Pull request merged**
