### PR TITLE
Origo master feature more option button

### PR DESCRIPTION
**Pull request by Polleryd**
Change as detailed in #1320

As an additional change, when layer is removable, a popup menu will open:
image

### CODE REVIEW

**Comment by tonnyandersson** [comment]
Nice work!

I noticed a few small things, though. Possibly more to come, so don't update this PR just yet.

- We mainly use Material Icons icons in the UI. I suggest using the `#ic_more_vert_24px` icon and `icon-smaller` button class. The icon is available in _css/svg/vendors/material-sprites/svg-sprite-navigation-symbol.svg_. Just copy it to the main _material-icons.svg_.
- Personally, I think the popup menu would look a lot nicer with a `box-shadow: $shadow`. I would have removed the border as well, but perhaps some users wouldn't like that.

**Comment by steff-o** [comment]
I have tested against WMS and WFS using Geoserver and it works like a charm. But I have some observations:

1. There are some unnecessary calls to _console.log()_
2. This PR does not use the high resolution prints from #1407, and that PR does not include the legend. So my suggestion is to wait until that has been merged and update this PR.
3. As with #1407, if a layer lacks style it crashes.

I noticed that _onRender_ is now _async_. Nothing wrong with that, I'm a huge fan of _async_ myself and something has to be a _promise_ when calling the server. But as there is no _await_, all errors except those swallowed when the remote call is performed, will end up as _uncaught (in promise)_. Maybe that is not a problem as previously I assume all errors would have ended up as _uncaught_ anyway as the way I understand it, the code that calls _onRender_ did not catch anything. But it could be worth contemplating if it affects anything else.

**Comment by asemoller** [comment]
> I have tested against WMS and WFS using Geoserver and it works like a charm. But I have some observations:
> 
> 1. There are some unnecessary calls to _console.log()_
> 2. This PR does not use the high resolution prints from [Printing in higher and lower resolution #1407](https://github.com/origo-map/origo/pull/1407), and that PR does not include the legend. So my suggestion is to wait until that has been merged and update this PR.
> 3. As with [Printing in higher and lower resolution #1407](https://github.com/origo-map/origo/pull/1407), if a layer lacks style it crashes.
> 
> I noticed that _onRender_ is now _async_. Nothing wrong with that, I'm a huge fan of _async_ myself and something has to be a _promise_ when calling the server. But as there is no _await_, all errors except those swallowed when the remote call is performed, will end up as _uncaught (in promise)_. Maybe that is not a problem as previously I assume all errors would have ended up as _uncaught_ anyway as the way I understand it, the code that calls _onRender_ did not catch anything. But it could be worth contemplating if it affects anything else.

Does this apply to this PR?

**Comment by steff-o** [comment]
@asemoller My bad. No it doesn't.

**Comment by tonnyandersson** [comment]
@Polleryd What's the reason for making the popup menu a component under the layer switcher (_overlays_) and render it on load (albeit hidden), rather than creating popup menu components on demand - and possibly add them to the respective layer component (_overlay_) - when clicking the _More_ button?

Personally, I don't see why the layer switcher need to be aware of the popup menu(s) at all. On the other hand, I haven't analyzed every aspect of this problem so maybe I'm missing something crucial here. Hence the question.

**Comment by tonnyandersson** [comment]
Also, rendering this stuff on load may make it more difficult to implement dynamically changing layer properties affecting the contents of the popup menu. Just a thought.

**Comment by Polleryd** [comment]
> @Polleryd What's the reason for making the popup menu a component under the layer switcher (_overlays_) and render it on load (albeit hidden), rather than creating popup menu components on demand - and possibly add them to the respective layer component (_overlay_) - when clicking the _More_ button?
> 
> Personally, I don't see why the layer switcher need to be aware of the popup menu(s) at all. On the other hand, I haven't analyzed every aspect of this problem so maybe I'm missing something crucial here. Hence the question.

I know the code is a bit confusing. The reason I did it this way is that the overlay component has position relative and therefore the popup cannot be shown outside the overlay component. But maybe I am missing some other way of doing this. I could maybe add the popup directly to <body> from the overlay component. If you have a good way of solving this I am all ears :)

**Comment by tonnyandersson** [comment]
I think it would be nice if the popup menu closed when clicking the _More_ button a second time.

Other than that, I think it all works quite well. I still have some issues with the implementation in general, though. For example, the _PopupMenu_ should probably have been implemented as a UI Component, with all the bells and whistles that comes with it. I know that the feature info popup is not implemented that way, but that doesn't mean this one shouldn't either.

However, since we are about to make a new release and this feature actually looks and works quite well, I think we can merge this anyway, given that you fix the popup menu closing issue i mentioned first.

**Comment by johnnyblasta** [comment]
When using tab to navigate it's possible to make the legend to freak out a bit, see animation.
LayerPropFocus3

**Comment by asemoller** [comment]
@johnnyblasta I get the same behavior on todays master when using tab.

**Comment by johnnyblasta** [comment]
> @johnnyblasta I get the same behavior on todays master when using tab.

Will have to make a issue for that when this is merged than. No point of fixing it before this is in since it concerns the same files.

**Comment by jokd** [comment]
Then let's merge this

**Review by tonnyandersson — APPROVED** [review]

**Pull request merged**
