### PR TITLE
added time as input type

### PR DESCRIPTION
**Pull request by jokd**
similar config as date and:
"type": "time"

### CODE REVIEW

**Comment by tonnyandersson** [comment]
Does not work very well in IE 11, it acts like a regular text field with no up/down arrow. Works better in Edge, but there you've got a scrollable dropdown thing that could use a little TLC style wise.

Any suggestions for IE?

**Comment by jokd** [comment]
IE? Just ignore it is my suggestion. There are polyfills like https://dan503.github.io/time-input-polyfill/ but I think that the placeholder is enough guidance for those who use unsupported browsers.

**Comment by tonnyandersson** [comment]
@jokd I'm cool with that. Then my only question is whether the placeholder should be "hh:mm" or "tt:mm" by default. Most (all?) of the GUI text is in swedish by default. Maybe this one should follow suit?

**Comment by jokd** [comment]
@tonnyandersson unless we are aiming for world domination I guess we could use swedish but then that should go for all the placeholders.
Either way works for me. Others?

**Comment by tonnyandersson** [comment]
@jokd Consistency is the key to success, they say. I say we should aim to use swedish in all default GUI texts and placeholders, at least until we internationalize Origo.

**Comment by jokd** [comment]
@tonnyandersson ok, I update all placeholders in this file

**Comment by daRasmussen** [comment]
Why not?
`var lang = navigator.language `

**Comment by jokd** [comment]
hmm... I like the thought of it but that is another issue I think. Along with different themes.

**Comment by daRasmussen** [comment]
@jokd I, Agree!

**Pull request merged**
