### PR TITLE
Make background buttons and close buttons in legend align on all browsers

### PR DESCRIPTION
**Pull request by huggla**
Style changes to make background buttons and close buttons in legend align on all browsers. Also removes some minor blank spaces.

bild

### CODE REVIEW

**Comment by tonnyandersson** [comment]
The close button still seems to be slightly misaligned, and it's not just that it's larger. 

image

**Comment by huggla** [comment]
> The close button still seems to be slightly misaligned, and it's not just that it's larger.
> 
> image

What browser and OS are you using?

**Comment by tonnyandersson** [comment]
Edge/Windows.

**Comment by huggla** [comment]
I've updated the style to align a little better on Edge/Windows. If I nudge the close button more downwards it will look bad on Firefox.

**Comment by tonnyandersson** [comment]
@huggla What does the firefox say if you set `margin: "3px 0"` instead of the current bottom only margin on the close button element?

**Comment by huggla** [comment]
That looked better. Thanks! I changed px to rem though.

**Review by tonnyandersson — APPROVED** [review]

**Pull request merged**
