### PR TITLE
Sharemap to measure control

### LINKED ISSUE #999: Measurement in shared map
**Is your feature request related to a problem? Please describe.**
When you share a map and has done measurements it would be nice to have them shown.

**Describe the solution you'd like**
If there is measurements on the map when clicking share map they would be saved and when the share link is used the measurements should be added to the map.

### LINKED ISSUE #1377: Measurements included in sharemap with added support of annotations
Is your feature request related to a problem? Please describe.
It would be useful if measurements was included while using the sharemap-control. 
Additionally being able to add annotations to the lines/polygons (measure-control) in form of a pop-up would also be useful.

### PR DESCRIPTION
**Pull request by johnnyblasta**
Closes #1377 and Closes #999 

Test by activate measure control and share map control with mapstate function.

### CODE REVIEW

**Comment by Grammostola** [comment]
Hi, for what it's worth I experience a crash when attempting to read a saved mapstate, regardless of whether measurements are in the map or not, with this branch. The master branch does not crash when attempting to read a saved mapstate (without measurements). I've tested with the latest origo server.

```
origo.js:721 
        
       TypeError: Cannot read properties of undefined (reading 'type')
    at GeoJSON.readFeaturesFromObject (webpack://Origo/C:/kod/share-measure/node_modules/ol/format/GeoJSON.js?:161:26)
    at GeoJSON.JSONFeature.readFeatures (webpack://Origo/C:/kod/share-measure/node_modules/ol/format/JSONFeature.js?:67:21)
    at Object.controlDraw [as draw] (webpack://Origo/C:/kod/share-measure/src/permalink/permalinkparser.js?:92:82)
    at eval (webpack://Origo/C:/kod/share-measure/src/permalink/permalinkparser.js?:86:37)
    at Array.forEach (<anonymous>)
    at Object.controls (webpack://Origo/C:/kod/share-measure/src/permalink/permalinkparser.js?:85:28)
    at eval (webpack://Origo/C:/kod/share-measure/src/permalink/permalink.js?:70:155)
    at Array.forEach (<anonymous>)
    at eval (webpack://Origo/C:/kod/share-measure/src/permalink/permalink.js?:69:29)
```

**Comment by Grammostola** [comment]
Hallo, the index.json is the default with a standard mapstate config.
The master branch does not crash when attempting to open a mapstate it has made, whereas this branch crashes when attempting to open a mapstate it has made. With no layers active and no measurements made this branch has made a mapstate like so:
```
{"layers":["osm/v/1/s/0/o/100","origo-mask/v/1/s/0/o/25"],"center":"2192543,9288853","zoom":"9","controls":{"draw":"","measure":{}},"map":"index"}
```

**Comment by johnnyblasta** [comment]
> Hallo, the index.json is the default with a standard mapstate config. The master branch does not crash when attempting to open a mapstate it has made, whereas this branch crashes when attempting to open a mapstate it has made. With no layers active and no measurements made this branch has made a mapstate like so:
> 
> ```
> {"layers":["osm/v/1/s/0/o/100","origo-mask/v/1/s/0/o/25"],"center":"2192543,9288853","zoom":"9","controls":{"draw":"","measure":{}},"map":"index"}
> ```

Fixed this now. I happened to create a empty state for draw, which it didn't like since it didn't checked for value before using.

**Comment by Grammostola** [comment]
Works much better now : )  A minor thing I noted is that if a map is shared while the measure tool isn't active it is when the shared map is opened (regardless of whether there were measurements in the shared map)

**Comment by jokd** [comment]
@Grammostola Is it ok to merge or shall @johnnyblasta fix your comment regarding the tools state when opening a shared map?

**Comment by johnnyblasta** [comment]
> @Grammostola Is it ok to merge or shall @johnnyblasta fix your comment regarding the tools state when opening a shared map?

I'm going to send in an adjustment soon.

**Comment by Grammostola** [comment]
Hi, with an empty map and the measurement tool not having been activated, if share the map I get a state like so
```
{"layers":["osm/v/1/s/0/o/100","origo-mask/v/1/s/0/o/25"],"center":"1639553,8937364","zoom":"9.333333333333332","controls":{"measure":{}},"map":"index"}
```
and when I open it in another tab the measure tool is active. If I remove measure from the controls object in the mapstate the measure tool is not active when I open the mapstate.

**Comment by johnnyblasta** [comment]
> {"layers":["osm/v/1/s/0/o/100","origo-mask/v/1/s/0/o/25"],"center":"1639553,8937364","zoom":"9.333333333333332","controls":{"measure":{}},"map":"index"}

Strange I didn't see this behavior, but when I removed the plugins I had in my index.html it showed up.
Now when the active state is stashed/restored it looks better.

**Comment by Grammostola** [comment]
Lgtm. (Tried without plugins and together with draw).

**Review by Grammostola — APPROVED** [review]

**Pull request merged**
