### PR TITLE
Adds a Content-Security-Policy

### LINKED ISSUE #1334: Add a Content-Security-Policy
**Is your feature request related to a problem? Please describe.**
To make the pages more secure and don't leak privacy information a Content-Security-Policy is good to have. Nice page to test your pages: [https://webbkoll.dataskydd.net/sv](url)

**Describe the solution you'd like**
Add a Content-Security-Policy to the demo-page to act as a example of how to secure the page.

### PR DESCRIPTION
**Pull request by johnnyblasta**
Closes #1334

### CODE REVIEW

**Review by jokd — APPROVED** [review]

**Comment by jokd** [comment]
Tried on our web map and got this:
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-O61tfZp/aDhcL8nyV1f8HcikmNvkoXIOADVYHxC57PA=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-5GTBAHUtU9TO/CzM287r+9RLjA2U1yINKIMC715Z23M='), or a nonce ('nonce-...') is required to enable inline execution.

Do I have to create a new hash for each build?

**Comment by jokd** [comment]
How about using 
`script-src 'self' 'unsafe-eval' 'nonce-0rigo'` instead and then

```
<script type="text/javascript" nonce="0rigo">
	var origo = Origo(...............
```

but perhaps that is less secure. I'm afraid hashing the build will make lots of applications not work as well as issues keeping index.html in sync with the build. In production, adding the hash can be a recommendation.

**Comment by jokd** [comment]
Found another issue; when changing the opacity of a layer:
image

**Comment by johnnyblasta** [comment]
The hash isn't for the Origo script. It's for the inline script that starts Origo. You could use 'unsafe-inline' instead of a hash, but the script that starts Origo doesn't change that often, so it isn't to much bother changing the hash for the hash which is shown in the error message.

**Comment by jokd** [comment]
Ok. But the issue with the event handling is something else,

**Comment by johnnyblasta** [comment]
> Ok. But the issue with the event handling is something else,

 'unsafe-inline' and removing the hash solves this, but much of the purpose of the CSP is gone then :(

**Comment by jokd** [comment]
Yes, better to rewrite code where necessary but that may take some time. Maybe should have 'unsafe-inline' until that work has been done?

**Comment by johnnyblasta** [comment]
Mad a new PR that adds the 'unsafe-inline' #1339 since this was already merged.

**Comment by tonnyandersson** [comment]
@johnnyblasta @jokd Yo, I noticed something when using the old [Origo 2.2.0 test config](https://www.malardalskartan.se/origo/v2.2.0/test.json):

image

Same issue for all vector type layers, i.e. AGS_FEATURE, WFS and external GEOJSON, TOPOJSON. Tested with a different config as well, same result.

Is this an actual issue or am I missing something?

**Comment by jokd** [comment]
We are creating our own CORS-issues :)

**Comment by jokd** [comment]
You would have to use  `connect-src 'self' kartor.vast......se` in order to get data from another domain. wms services are images so they are allowed from anywhere since `img-src *`

**Comment by tonnyandersson** [comment]
Ah. A classic case of RTFM then.

**Comment by jokd** [comment]
Usually don't go that far but yes indeed.

**Comment by johnnyblasta** [comment]
This Content-Security-Policy should be considered as a good starting point, there is often the case it has to be modified when added to your local environment.

**Pull request merged**
