### PR TITLE
WMS getLegendGraphic option

### PR DESCRIPTION
**Pull request by tonnyandersson**
Rough draft that solves #258.

### CODE REVIEW

**Comment by tonnyandersson** [comment]
Contains two options - get full legend as a single image or get a symbol for each rule in the SLD.

The first option requires no other configuration than setting layer style to "getLegendGraphic", like this:
```json
"style": "getLegendGraphic"
```
Option number 2 requires a style defining rules found in the relevant SLD (see example below). The rules are defined by name and title. The name **must** be the same as the name of the rule in the SLD. The title is optional and is only used for labelling in the legend.
```json
"wms_style": [
  [{
    "sldRules": [
      {
        "name": "Rule1",
        "title": "Rule 1 objects"
      },
      {
        "name": "Rule2",
        "title": "Rule 2 objects"
      },
      {
        "name": "Rule3",
        "title": "Rule 3 objects"
      }
    ]
  }]
]
```

The first option - getting full legend - is preferable for raster styles, e.g. ColorMap etc. Main downside is that the legend is styled by Geoserver and does not blend well with the Origo legend. Looks a bit tacky.

The second option only gets the actual symbol for each rule and uses it as symbol in the legend. Looks a lot better than the first option, but relies on defined rules, both in the Origo config and SLD. The configuration could be made easier by retrieving the SLD from Geoserver automagically, and getting all the rules that way. AFAIK, this would require using the Geoserver REST API, which requires authentication (unless authentication has been disabled). Would be a cool solution, though, but perhaps not as generic since it depends on back-end configurations.

Any thoughts?

**Comment by markus659** [comment]
Thanks for contributing @tonnyandersson. I don't think we need to look at anymore advanced way of handling styling from SLD, at least not currently. If the need occurs, we can revisit it at that point.  

One thing I noticed with the code is that when it replace the source url it expects ows in the url. Perhaps it can be rewritten so that it replaces the last four characters with ```/wms?``, or even just the last three? I'm thinking of these:
```javascript
var url = source.url.replace("/ows", "/wms?");

```
 I configured my source as https://karta.hallstahammar.se/geoserver/wms which obviously did not work with the way it is written now.

I don't know if we should wait for the first release before merging this? What do you think  @afogelberg @jokd?

**Comment by tonnyandersson** [comment]
I agree with your suggestions, @markus659. Unfortunately, I have not been able to set up a decent development environment at my new place yet, so it may take a while before I get around to update the code.

On the other hand, Eskilstuna is working on a different solution with external help. Is theirs a better solution or is it too specific for Eskilstuna's needs to fit the Origo core?

**Comment by afogelberg** [comment]
I think this is a little bit tricky. As I understand the ows/wms way of writing url:s is only used by GeoServer. I haven't looked at Eskilstunas solution and eSamverkan is also working on a solution. Anyways, as you say @markus659 , lets at least wait until after the first release.

**Comment by tonnyandersson** [comment]
For the record, it seems eSamverkan is running some sort of hybrid solution. For non-thematic layers, only the symbol is retrieved. For thematic layers, the full legend is retrieved in one image. I will look into the details when I'm up and running developmentally.

**Pull request closed without merging**
