### PR TITLE
PR for Infowindow and selection manager 

### PR DESCRIPTION
**Pull request by imantahriri**
Infowindow is the given name for an alternative tool to show the information about one or more selected feature(s) on the map. 

one small change in the index.json file is required as `overlay: true / false` should be changed to `infowindow: infowindow / overlay / sidebar`.

Choosing infowindow lets user to see all the selected features and highlight or deselect each one of them. Besides, features will be shown in different groups, each group representing a layer or a group-layer. 

All selected features can be sent to an external service. Features of layers marked with "simpleExport" in the config will be sent to a simple service in origo-server (comes in a seperate PR) and features of layers marked with "layerSpecificExport" can be sent to any given external service to create an ecxel or pdf list of features or any other possible analysis .

A "Selection manager" is associated with this tool that has the responsibility of storing selected features, adding features to them, removing from them and other managerial logic. Infowindow is the representational part of.

The main purpose of the Selection manager is to be central brain of the application regarding selecting/deselecting features and all other tools like multi-selector and search etc should simply deliver an item/several items and manager should do the rest.

Note that selectionmanager module IS but infowindow module IS NOT converted to Origo 2 format.

### CODE REVIEW

**Comment by asemoller** [comment]
This pr fixes issue #516 and #744.

A config with all settings are in progress.

**Comment by asemoller** [comment]
Se this [config](https://karta.sigtuna.se/arbmat/pr_861/index.json).

What does "All checks have failed" mean @daRasmussen?
What can we do to fix it?

**Comment by daRasmussen** [comment]
@asemoller checking

**Comment by daRasmussen** [comment]
@asemoller [Hope this helps](https://github.com/origo-map/origo/pull/863)

**Comment by jokd** [comment]
Tested and works as expected besides the behaviour of clicking the row/arrow in the infowindow. I suggest clicking a row should always select the feature (and perhaps expand the rows info/collapse the other rows), and the arrow should just toggle the info (expanded/collapsed). See attached gif.
I haven't tested the export functions.
Besides that I get some linter errors in Atom that should be taken care of.
gif

**Comment by daRasmussen** [comment]
@asemoller @imantahriri All checks have passed

**Comment by tonnyandersson** [comment]
Clicking around in the infowindow seems to work fine now but I'll let @jokd have the last word on that since he brought it up.

Exporting to Excel works like a charm, except for one thing. There seems to be some inconsistencies regarding how the geometry attribute is handled at export depending on layer type. Or rather, depending on *map server* type. The function is hardcoded to delete the `geom` attribute, but "geom" is not a standard geometry attribute name. ESRI services, for instance, uses the name "geometry".

I suggest using the `feature.getGeometryName()` function to obtain the actual geometry name before removing the property, instead of using the hardcoded `obj.geom`.

**Comment by imantahriri** [comment]
> Clicking around in the infowindow seems to work fine now but I'll let @jokd have the last word on that since he brought it up.
> 
> Exporting to Excel works like a charm, except for one thing. There seems to be some inconsistencies regarding how the geometry attribute is handled at export depending on layer type. Or rather, depending on _map server_ type. The function is hardcoded to delete the `geom` attribute, but "geom" is not a standard geometry attribute name. ESRI services, for instance, uses the name "geometry".
> 
> I suggest using the `feature.getGeometryName()` function to obtain the actual geometry name before removing the property, instead of using the hardcoded `obj.geom`.

That was a really good point @tonnyandersson, fixed now.

**Comment by jokd** [comment]
@imantahriri There are still linter issues in eg featureinfo.js and getfeatureinfo.js

**Comment by jokd** [comment]
LGTM

**Pull request merged**
