### PR TITLE
Handle overflow in print settings with scrollbar

### PR DESCRIPTION
**Pull request by johnnyblasta**
image

### CODE REVIEW

**Comment by jokd** [comment]
Tested and works well in Edge and Chrome. Could have some spacing in the bottom but I'll approve it.
image

**Review by jokd — APPROVED** [review]

**Comment by johnnyblasta** [comment]
Could someone test it on iOS and other mobile devices?

**Comment by johnnyblasta** [comment]
> Could someone test it on iOS and other mobile devices?

Don't behave as expected on iPhone, either in Safari or Chrome.
Works well in Internet Explorer though.

**Comment by johnnyblasta** [comment]
Now it should work with iPhone also.

**Pull request merged**
