### PR TITLE
Awesomplete

### LINKED ISSUE #317: Search is unavailable on Andriod
The search field is visible but unavaible for data input. It auto closes when the field is selected for input. This occurs on Samsung using both Samsungs internet and chrome.

### PR DESCRIPTION
**Pull request by afogelberg**
This PR fixes #317 #318 #350 . With this PR typeahead is replaced with the much lighter awesomplete, also meaning that we will get rid of the dependency to jQuery for the autocomplete library.

With this PR also a division is introduced for the search list. The limit will portion an equal number of hits for each searchable layer with hits. 
awesomplete

### CODE REVIEW

**Comment by jokd** [comment]
I have tested and have a couple of issues. 
First when the response contains an é (could be other special characters as well) the result list gets buggy and presents all results in one group. 
I have also noted that when continuing to type the search frase, instead of emptying the list when the server sends an empty response the list is intact. Is this the expected behaviour?
The same happens when I type a search frase, empty the search field and then type something that doesnt result in any hits. The result list will then present the results from before I emptied it.

**Comment by afogelberg** [comment]
> I have also noted that when continuing to type the search frase, instead of emptying the list when the server sends an empty response the list is intact. Is this the expected behaviour?

This is expected behaviour. Would you prefer to not keep previous result as a cache?

**Comment by afogelberg** [comment]
> First when the response contains an é (could be other special characters as well) the result list gets buggy and presents all results in one group.

I don't get this problems with special characters. But maybe we have different encodings in the server response?

**Comment by jokd** [comment]
> This is expected behaviour. Would you prefer to not keep previous result as a cache?

Im not sure. It wasnt like that before but it might be a nice feature. 
But when clearing and searching again I think the cache should be wiped away.

**Comment by jokd** [comment]
>I don't get this problems with special characters. But maybe we have different encodings in the server response?
UTF-8 ?

**Comment by jokd** [comment]
I found the bug. It seems to have little to do with charsets or special characters. 
In the `groupToList`-function in search.js theres a .splice-method inside the forEach that can cause results not being displayed. One solution is to instead use a for-loop and back the index when splicing.

`    for (var index = 0; index < types.length; index++) {
      var type=types[index];
      if (nr < limit) {
        var item = group[type][turn];
        if (type in selection === false) {
          selection[type] = [];
        }
        selection[type][turn] = item;
        if (!group[type][turn + 1]) {
          types.splice(types.indexOf(type), 1);
          index--;
        }
      }
      nr++;
    };`

**Comment by jokd** [comment]
@afogelberg Now it works as expected. Well done!

**Comment by afogelberg** [comment]
Ok to merge?

**Comment by jokd** [comment]
Can't see why we shouldn't =)

**Pull request merged**
