### PR TITLE
Validate input

### PR DESCRIPTION
**Pull request by mulfvik**
Address issue #323

### CODE REVIEW

**Comment by jokd** [comment]
Are input types "decimal" and "integer" valid html? Otherwise type should be "number". Setting step="1" will only allow integers while step="any" will allow integers as well as decimal values.

**Comment by mulfvik** [comment]
@jokd I guess its not not valid html but it could be hard to read so I will change that.

**Comment by jokd** [comment]
Seems to do the job, can't see why we wouldn't merge this.

**Comment by mulfvik** [comment]
Just one thing, one should be able to use multiple cases of types. Will handle that in next coming commit.

**Comment by johnnyblasta** [comment]
Have tested the latest fix for multiple of same type and it LGTM.

**Pull request merged**
