### PR TITLE
Searchlist in infowindow

### LINKED ISSUE #1413: Improve how the search results are presented
We need to be able to see all hits when we do a search in Origo. One suggestion is to design the  window  for the search results in the same way as the information window. That way it is possible to get a nice overview with all results presented in bundles and we will keep a consistent look.

### PR DESCRIPTION
**Pull request by jokd**
Fixes #1413 
Adds a infowindow-component which can be used to create a floating infowindow or aligned to the left.
Search control is configured ike this:
{
"name": "search",
"options": {
	...
	"autocompletePlacement": "search", //can be search, left or floating (defaults to search)
	"searchlistPlacement": "left" //can be search, left or floating, activated by hitting enter (defaults to nothing)
}
}

### CODE REVIEW

**Comment by tonnyandersson** [comment]
Tested with old default test config (v. 2.2.0). Using anything other than `"search"` for `"autocompletePlacement"` or `"searchlistPlacement"` results in this error:

image

image

**Comment by jokd** [comment]
I suppose the structure of our search responses differ. I will look into it.

**Comment by jokd** [comment]
This feature works when using Option 1 for search:
```
   * Option 1. Feature info is requested from a map service.
   * In this case idAttribute and layerNameAttribute must be provided.
   * A map service is used to get the geometry and attributes. The layer is defined
   * as an ordinary layer in the layer config section.
```
Will have to make adjustments to support the other variants as well. But maybe I await this PR first: https://github.com/origo-map/origo/issues/1420

@MattiasSp Are you looking into this?

**Comment by jokd** [comment]
Replaced with #1751 to get a clean commit history

**Pull request closed without merging**
