### PR TITLE
Moved exportFileName and some small fixes

### PR DESCRIPTION
**Pull request by asemoller**
Made it possible to have multiple exports for a layer with different file extensions.
Fixes issue #941 .

Also made some changes for error message, filename and button text.

### CODE REVIEW

**Comment by jokd** [comment]
Isn't a default value for filename a good idea? What will the file be named if the option is omitted?

**Comment by asemoller** [comment]
I agree that default values are to prefer.

In this case we can send data to any service that returns something. What it returns and in what format can differ. If the service returns anything as a file, then the file must be defined by its file extension. This will then negate the necessity of default values. To ensure that the administrator thinks things through, specifically the file extension, I think it is better to have it as a required field instead. A default value would just be wrong as we would have to presume which file extension is implied.

**Comment by jokd** [comment]
I see but could a default name, like the date and time, be set and then the file type (as in extension) come from the service?

**Comment by asemoller** [comment]
That would probably work and be a much better solution. However I just try to clean up the existing code without the intention to present a final solution.

**Pull request merged**
