### PR TITLE
adds searchList

### LINKED ISSUE #463: Search list
It would be nice to add an input type (called search list) to the edit form. Basically its a drop down that supports search. 

Edit form specification: 
`... attributes: [ { name: name, tiltle: title, type: searchList: list [ ... ], config: { ... } }]`

Config options: 
- Only text, behaves like a drop down with a search function.
   ` ... list : [{ value: text }] `
- Attach an icon.
  ` ... list : [{ value: text, src:  src }] `
- Creates a library.
  ` ... list : [{ location: path, extension:  png }] `
- Additional options: 
  - Minimum characters the user has to type before the autocomplete popup show up
    ` ... attributes: [ ... list[ ... ], config: { ... minChars: 0 ... } ]`
  - Maximum number of suggestions to display.
    `... attributes: [  ... list[ ... ], config: { ... maxItems: 5 ... } ]`

### PR DESCRIPTION
**Pull request by daRasmussen**
This is an updated PR of PR #604 
Fixes #463

### CODE REVIEW

**Comment by jokd** [comment]
Tested and have some comments:
The function is case sensitive, I would prefer the opposite.
When I try to add a second point, I can no longer expand the dropdown, sometimes happens also with the first point.
Sometimes I have to type one sign before the suggestions appear, sometimes two.
I suggest removing the border for the arrow button. (.o-map #searchList .awesomplete .dropdown-btn)

**Comment by tonnyandersson** [comment]
Tested and I agree with previous reviewer on all points.

On a sidenote, I think it would be cool with consistent styling of the different dropdown types in the edit form. Now, the searchlist dropdowns look different from the default dropdowns (different arrow icon, no background change on hover etc.).

**Comment by daRasmussen** [comment]
@jokd I have made some changes to searchList and tried to comply with your comments. See changelog for details and thank you for you input. 

@tonnyandersson tnx for you input, I agree on dropdown styles but I thinks this should be an separate issue.

Regarding todo in changelog, those issues should be separate issues/PRs. I think that this PR has grown to much and "new" features should be documented as feature requests. I also have modified the searchList behavior to match the dropdown behavior for accessibility purposes, but I think there is more to be done in this area for speech readers and those issues should be separate features requests.  

Give it a try and come back to me with comments. 


# ChangeLog
# CSS 
Removes border on button. 
Displays border on button focus (for usability). 
adds highlight style 
adds highlight style on hover (for usability). 

# JS 
fixes correct awesomeplete instance is selected on new feature. 
fixes correct awesomeplete instance is selected on feature edit.
fixes value stored in input on edit.
fixes marker for options with images. 
fixes marker selection to mark parts of list option. 
adds open menu on enter when input is in focus (for usability).
adds arrow key selection when menu is open (for usability). 
adds support of required
adds validation if required is specified only list items are valid options.
adds required input cannot be empty.

# TODO / Feature Requests
Add list selection with arrows when menu opens with btn on focus (for usability). 
Display selectable menu if input is not part of list.

**Comment by jokd** [comment]
Works and looks much better now. I was a bit confused at first when I got strange suggestions as in my example:
image


Then I realised it also looks at the filenames and then it makes sense.

**Comment by daRasmussen** [comment]
@jokd I can look into that.

**Comment by jokd** [comment]
@daRasmussen I think the way it works now is ok

**Comment by tonnyandersson** [comment]
@daRasmussen I think the dropdown button still looks a bit off when pressed. The border goes outside the input box in a weird way.

image

I don't think that styling issues (e.g. new dropdown vs old dropdown) should be regarded as separate issues. If a new feature is implemented, it should look and feel like the rest of the UI, as far as practicable. However, if a new, more up-to-date feature is added and the addition calls for a more extensive overhaul of the existing UI, separate issues may be appropriate.

That said, I know this PR has been in the works for quite some time now, and I understand that you are eager to close the books on it. So I'll allow the styling irregularities for now, but please make sure to file new issues regarding this later on.

Oh, before I approve... The new build files, are they necessary? Please correct me if I'm wrong here, but I thought we only updated the build files when making new releases.

**Comment by daRasmussen** [comment]
@tonnyandersson I don’t see any build files https://github.com/origo-map/origo/pull/1005/files

**Comment by tonnyandersson** [comment]
@daRasmussen LOL! Sorry, my bad. Was looking at #604 for some reason. So, all good.

**Review by tonnyandersson — APPROVED** [review]

**Pull request merged**
