### PR TITLE
Formatting of the title

### LINKED ISSUE #1033: Print - Be able to format the title and description
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to change the alignment of the title/description and also change the size.

**Describe the solution you'd like**
Next to the title there should be a button to open options for adjustments, see image.
image
When opened button for alignment and dropdown for size should be shown, see image.
image

### PR DESCRIPTION
**Pull request by johnnyblasta**
Fixes #1033 

Makes it possible to change alignment and size of the title for the printed map.
image

### CODE REVIEW

**Comment by johnnyblasta** [comment]
Also adding the same formatting options for description.

**Comment by jokd** [comment]
Works well. Maybe use the same checkboxes as the size rather than a dropdown, and name the sizes small-big rather than h1-h5?

**Comment by johnnyblasta** [comment]
> Works well. Maybe use the same checkboxes as the size rather than a dropdown, and name the sizes small-big rather than h1-h5?

I opted out of using buttons since it was more than 3 sizes, so hasn't tested how it would look, but perhaps it could work. I used the classnames for the header, since it was the easiest. Don't know what to call all of the sizes :)

**Comment by jokd** [comment]
Perhaps 3 sizes are enough?

**Comment by johnnyblasta** [comment]
> Perhaps 3 sizes are enough?

Perhaps, since there are a very slight difference between some of the 5 headings.

**Comment by johnnyblasta** [comment]
Made the sizes configurable, kept the dropdown.

**Comment by jokd** [comment]
I guess I can live with it being a dropdown, but I find the settings page a bit messy now when there's a lot of stuff going on. Uniforming the spacing between headers and content and adding a delimiter between the expanded description settings and the page size setting might straighten things up:
image

This is related to #1030 as well.

**Review by jokd — APPROVED** [review]

**Comment by johnnyblasta** [comment]
Fixed spacing and added divider

image

**Pull request merged**
