### PR TITLE
Added active option

### LINKED ISSUE #747: Option to activate geoposition on start
Autostart geoposition together with zoomlevel would be a nice feature.

### PR DESCRIPTION
**Pull request by jokd**
Fixes #747 
```
    {
      "name": "geoposition", 
      "options": {
        "active": true,
        "zoomLevel": 14
      }
    }
```

### CODE REVIEW

**Comment by tonnyandersson** [comment]
@jokd Did we talk about an option to activate the geolocation _without_ panning to the location as well?

**Comment by jokd** [comment]
@tonnyandersson We talked the talk but I have yet to walk the walk.

**Comment by tonnyandersson** [comment]
@jokd Are you planning to walk the walk in this PR or is that a different issue?

**Comment by jokd** [comment]
We can address that in another issue if this is ok to merge.

**Comment by tonnyandersson** [comment]
Works for me.

**Pull request merged**
