### PR TITLE
fix: search result not hidden in legend search

### LINKED ISSUE #1641: Legend search - the list of results is only displayed within the legend
**Is your feature request related to a problem? Please describe.**
The list of results from the legend search is only displayed within the legend window. If you search in a legend with, for example just one group, you may not see all search results.

**Describe the solution you'd like**
The result list should display regardless of the size of the legend.

legend-search-result-list

### PR DESCRIPTION
**Pull request by johnnyblasta**
Fixes #1641 
Had to set a fixed width to input and result list to not have it runaway outside page. Perhaps some css guru has a fix for this?

### CODE REVIEW

**Comment by johnnyblasta** [comment]
Damn, I found a bug with this myself. Will try to rework it.

**Comment by johnnyblasta** [comment]
> Damn, I found a bug with this myself. Will try to rework it.

Bug handled.

**Comment by johnnyblasta** [comment]
Demo
Legend search

**Comment by Grammostola** [comment]
Hi, it seems to fix the reported issue, nicely done.

I noted that if the legend search is specified to be able to search layer names (that won't auto rewidth the legend) the hit list can run off the page. If it could detect the end or perhaps the legend width and newline there that could be good.

**Comment by johnnyblasta** [comment]
> Hi, it seems to fix the reported issue, nicely done.
> 
> I noted that if the legend search is specified to be able to search layer names (that won't auto rewidth the legend) the hit list can run off the page. If it could detect the end or perhaps the legend width and newline there that could be good.

Put a max-width on search result, so that a new line is forced on long results and it don't falls outside screen.

**Comment by Grammostola** [comment]
It seems the black search hit area does respect the max width though long names don't. An arbitrary newline in a layername might not be the best way to handle the situation.
bild

**Comment by johnnyblasta** [comment]
> It seems the black search hit area does respect the max width though long names don't. An arbitrary newline in a layername might not be the best way to handle the situation. bild

Can solve it with `overflow-wrap: break-word;` and it will break the long word at arbitrary place:
image

Is this the preferred way to handle it? @Grammostola

**Comment by Grammostola** [comment]
Hahaha, good example. Yes I definitely think it is the way.

**Comment by Grammostola** [comment]
I quite like it. When the legend is very wide it can look a bit funny but I think that is preferrable to a layer name or perhaps abstract running off the page. So while it does look good to me, it being a cosmetics issue the more eyes the merrier

**Pull request merged**
