### PR TITLE
Fixes #342

### LINKED ISSUE #342: Zoom to feature in permalink
Being able to zoom to a certain feature in permalink would be nice.

### PR DESCRIPTION
**Pull request by daRasmussen**
In permalinkparser.js are examples of how to use this function.

### CODE REVIEW

**Comment by daRasmussen** [comment]
#342

**Comment by tonnyandersson** [comment]
Is this intended as a replacement for PR #343 or is it presented as an alternative fix?

Ping @jokd.

**Comment by jokd** [comment]
@daRasmussen Shall we close this?

**Comment by daRasmussen** [comment]
@jokd no need.

**Pull request closed without merging**
