### PR TITLE
Respects the extent property of a layer

### LINKED ISSUE #1025: WFS layer doesn't respect extent in GetFeature request
**Describe the bug**
When limiting a layer with the extent prooperty, this is not respected when making the GetFeature request. 

**To Reproduce**
Set extent on layer level in the config
Pan outside the extent area
Activate layer
Request will not consider the extent bounds

**Expected behavior**
No requests for features outside the extent

### PR DESCRIPTION
**Pull request by jokd**
Fixes #1025

### CODE REVIEW

**Comment by jokd** [comment]
@daRasmussen Any idea how to handle the build errors in Travis CI? Seems to only affect Node 10 in osx environment.

**Comment by tonnyandersson** [comment]
@jokd Works like a charm! But I'll wait for the Travis thing to get sorted before I give it my official seal of approval.

**Comment by tonnyandersson** [comment]
@jokd Noticed that this bug seems to affect vector layers in general. The same issue can be seen in GeoJSON layers, for example. There's also an open ticket regarding this in the OL repo, see issue 11651.

**Review by daRasmussen — APPROVED** [review]
LGTM

**Comment by jokd** [comment]
Solved in OL 6.6.1

**Pull request closed without merging**
