### PR TITLE
Sass clean up

### PR DESCRIPTION
**Pull request by daRasmussen**
Fixes issue #1077

### CODE REVIEW

**Comment by daRasmussen** [comment]
This clean up is based on "stylelint-config-sass-guidelines" with additional rules. More about stylelint, css loaders and additional rules will come soon. For now, this is just a clean up of the CSS/SASS code to improve readability, consitency and performance.

**Comment by mulfvik** [comment]
Hi @daRasmussen !
This linter rules doesnt allow camelcase naming of classes?
In the commit below the classname is changed from errorMsg to errormsg..
commit 6798f09edc0dfc0c11c2de390d64b75fe0400ee5

**Comment by mulfvik** [comment]
@daRasmussen ...so this breaks the styling of error message when validating editform. Should I create an issue/PR on this?

**Comment by daRasmussen** [comment]
@mulfvik more info is coming about linting settings of stylus. Sorry for delay.

**Comment by mulfvik** [comment]
No hurry @daRasmussen

**Pull request merged**
