### PR TITLE
Embedded map interaction

### LINKED ISSUE #275: Posibility to turn off zoom function for embeded maps
In a webpage where you have an inbeded map you get stuck in the map zoom, instead of scrolling by in the webpage.
It would nice to be able to turn off the zooming function for embeded maps.

### PR DESCRIPTION
**Pull request by jokd**
Fixes #275

### CODE REVIEW

**Comment by jokd** [comment]
Perhaps the changes to tasks/webpack.prod.js are no longer necessary, will look into that.
To test this simply create a new document and add the map as iframe:
<iframe src="index.html" style="width:100%;height:400px;"></iframe>

**Comment by jokd** [comment]
Readded the uglifyjs plugin since it cuts some kB of the build size.

**Comment by tonnyandersson** [comment]
@jokd Is the `webpack.optimize.AggressiveMergingPlugin()` no longer needed?

**Comment by jokd** [comment]
No it seems redundant. At least build size wise.

**Comment by tonnyandersson** [comment]
@jokd Cool. You could probably remove the webpack import as well then, right?

**Comment by jokd** [comment]
Sounds right

**Comment by Grammostola** [comment]
Tried it briefly on a mobile device & desktop and I saw no issues. Seems like a nice improvement for embedded maps that take up most/all of a page's width, that you want to be able to scroll past without engaging.

**Comment by CBEskilstuna** [comment]
Tested on Pixel Android v10 with Chroooome and it works good

**Comment by jokd** [comment]
OK to merge?

**Comment by CBEskilstuna** [comment]
Yes

**Comment by tonnyandersson** [comment]
@jokd Just take a look at that webpack import before you merge.

**Pull request merged**
