### PR TITLE
Updates getattributes.js

### LINKED ISSUE #547: Value 0 is interpreted as undefined
If attribute value is null or a number (not string) it does not show in the popup which can be misleading.

### PR DESCRIPTION
**Pull request by daRasmussen**
fixes #547

### CODE REVIEW

**Comment by tonnyandersson** [comment]
Not sure if this is the preferred behaviour regarding null values. Personally, I prefer a cleaner popup, without a bunch of null value attributes listed. But I understand it can be seen as a bit misleading depending on type of application and intended use.

0 values, on the other hand, is a different story. That should definitely be regarded as a bug.

**Comment by daRasmussen** [comment]
@tonnyandersson I agree that Null values are undesired in the popup. Which would mean that strings like "Null", "undefined", "NaN", "Infinity", "[]" and "{}" would also be undesired in the popup as preferred behaviour?

**Comment by tonnyandersson** [comment]
Well, I guess "Null", "undefined", "[]" and "{}" can be regarded as different representations of "empty" and should therefore, in my opinion, not be shown in the popup. "NaN" and "Infinity", on the other hand, indicates potential errors in the data. Not sure if those should be treated the same way.

**Comment by daRasmussen** [comment]
@tonnyandersson Maybe we could solve these issues with a attribute mode option like:

- verbose, shows all 
- errors, shows only errors in data
- default, removes errors and empty (is default)

Any thoughts @markus659 @jokd

**Comment by jokd** [comment]
@daRasmussen Go ahead with the attribute mode option as suggested.

**Comment by jokd** [comment]
Can we solve this value 0 bug now and look into the attribute mode option thing later if there is much work involved?

**Comment by tonnyandersson** [comment]
@daRasmussen I agree with @jokd regarding his last comment. The 0 value bug is a quite serious bug that needs to be fixed immediately.

**Comment by jokd** [comment]
If this PR solves the "0 value bug" I think we should merge it and perhaps later pick up the issue regarding the other possible values.

**Comment by tonnyandersson** [comment]
Yep, this PR solves the "0 value bug". TMNT. Merge it.

**Comment by jokd** [comment]
FTW

**Pull request merged**
