### PR TITLE
Extended legend zoom

### LINKED ISSUE #663: Legend graphics zoom
Legend graphics size is limited to the size of the legend, thus forcing larger legend graphics to shrink to a smaller size, potentially making the legend graphics illegible.

Legend graphics should be zoomable if its original size is larger than the size of the legend.

### PR DESCRIPTION
**Pull request by tonnyandersson**
Fixes #663.

Use [this config](https://gis.hudiksvall.se/examples/ext_legend_zoom.json) for testing.

### CODE REVIEW

**Comment by jokd** [comment]
@tonnyandersson Is this supposed to work with simple icons as well? Can you supply a config for testing?

**Comment by tonnyandersson** [comment]
Not originally intended to work with simple icons.

See first comment for test config.

**Comment by jokd** [comment]
@tonnyandersson It's not working with your supplied config either. Maybe I am missing some dependencies? I get "Query variable mapStateId not found" on loadresources.js, can this have something to do with it?

**Comment by johnnyblasta** [comment]
@jokd "Query variable mapStateId not found" har med att göra med dela karta, så den kan du nog bortse ifrån.

**Comment by daRasmussen** [comment]
I mentioned this in my review of PR#618

I get this prompt even when I don't use extended sharemap functionality.

_Originally posted by @daRasmussen in https://github.com/origo-map/origo/pull/618/files/7f5d66b01337c22b673640780417c79e5f9ed392_

**Comment by tonnyandersson** [comment]
@jokd Sorry, my bad. New URL in my first comment now.

@daRasmussen Yes, and that issue was addressed. Now, you will only get that promp if you are using the extended sharemap functionality without loading a shared map state, which is exactly what the previously supplied config does.

**Comment by daRasmussen** [comment]
@tonnyandersson great success! Maybe that prompt could be moved to the prompt controller #662 ?

**Comment by johnnyblasta** [comment]
LGTM

**Pull request merged**
