### PR TITLE
Print IE and Edge fix

### LINKED ISSUE #1040: Print to PDF don't work for IE and Edge
**Describe the bug**
Print to PDF don't work for IE and Edge pre Edge Chromium

**To Reproduce**
Try to print to PDF and nothing will happen.

**Expected behavior**
A PDF should be created.

**Desktop (please complete the following information):**
 - Browser Internet Explorer and Edge pre Edge Chromium

### PR DESCRIPTION
**Pull request by johnnyblasta**
Fixes #1040

### CODE REVIEW

**Comment by johnnyblasta** [comment]
It would be nice if someone could approve this since I have another PR on queue.

**Comment by johnnyblasta** [comment]
> It would be nice if someone could approve this since I have another PR on queue.

Fixed it with a new PR, but nice if this can be tested anyway.

**Comment by jokd** [comment]
Tested in IE and it works, though it takes like 40 seconds to generate A4 pdf with OpenStreetMap. The png is generated in ~3 seconds.

**Comment by johnnyblasta** [comment]
> Tested in IE and it works, though it takes like 40 seconds to generate A4 pdf with OpenStreetMap. The png is generated in ~3 seconds.

Yes, noticed it took long time creating PDF, since it's basically the previous version it would have taken a long time before also?
Tested on my test server and on Edge it took 10 seconds and on IE it took 20 seconds.

**Comment by jokd** [comment]
> > Tested in IE and it works, though it takes like 40 seconds to generate A4 pdf with OpenStreetMap. The png is generated in ~3 seconds.
> 
> Yes, noticed it took long time creating PDF, since it's basically the previous version it would have taken a long time before also?
> Tested on my test server and on Edge it took 10 seconds and on IE it took 20 seconds.

Probably, I am not a frequent IE user and I think there's not much to do about it. I say we merge this.

**Pull request merged**
