### PR TITLE
Added blending modes, CSS filter

### LINKED ISSUE #1212: Layer blending and filter effects
Since each layer in a map can be treated as a separate HTML element (canvas), it is possible to manipulate the graphics of each layer through various CSS [blending modes](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode) and [graphics filters](https://developer.mozilla.org/en-US/docs/Web/CSS/filter). For example, one can blend two background maps to create pretty hybrid backgrounds or manipulate brightness, contrast, hue, saturation etc.

I think it would be nice to implement this as configurable layer settings.

image
*Two WMS layers with blending mode **multiply** set on the top layer and **brightness** and **contrast** filters set on the bottom layer to make it pop a little*

### PR DESCRIPTION
**Pull request by tonnyandersson**
Fixes #1212.

Just add `cssFilter` or `blendingMode` properties to any layer in the config. Please use the documentation on [CSS filters](https://developer.mozilla.org/en-US/docs/Web/CSS/filter) and [blending modes](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode) for guidance.

Examples:

~~`"cssFilter": "brightness(50%) contrast(10%)"`~~

~~or~~

~~`"blendingMode": "difference"`~~

"css": {"filter": "brightness(1.2) contrast(2)", "mix-blend-mode": "multiply"}

EDIT

Oh, and please note that IE is not particularly fond of any of this...

### CODE REVIEW

**Comment by jokd** [comment]
Works well, nice effects!
Perhaps just having a css-option on the layer will be enough (and open up for more css sorcery as well)
in config.json

"css": {"filter": "brightness(50%) contrast(10%)", "mix-blend-mode": "difference"}

and in layer.js:

    if (layer.get('css')) {
	  Object.assign(document.getElementsByClassName(layer.getClassName())[0].style, layer.get('css'));
    }

**Comment by tonnyandersson** [comment]
Not a bad idea. I'll fix.

**Comment by tonnyandersson** [comment]
Implemented changes mentioned in previous comments.

**Comment by jokd** [comment]
Awesome!

**Review by jokd — APPROVED** [review]

**Pull request merged**
