### PR TITLE
Scale picker issue #393

### PR DESCRIPTION
**Pull request by osram**
First pull request from Oemap. I hope I've followed the process correctly.
Tell me if something is off.

### CODE REVIEW

**Comment by tonnyandersson** [comment]
Seems to work as intended.

One issue, though: when removing the control from the config, the controls in the left toolbox stays in place, leaving an aesthetically displeasing empty space above.

image

I suggest a more dynamic positioning of the various toolboxes, e.g. when no tool is present in the top toolbox it should be collapsed/hidden, allowing the left toolbox to go all the way to the top. This is perhaps a more general issue rather than related to the scale picker issue specifically, and should probably be treated accordingly. Posting for awareness, mainly.

**Comment by osram** [comment]
I guess it would be fairly easy to make it collapse if empty. You want me to do it?

**Comment by tonnyandersson** [comment]
Sure, if you have the time and if you have a somewhat general solution in mind, something that isn't tied to the scale picker specifically.

**Comment by tonnyandersson** [comment]
Replaced and fixed with #725.

**Pull request closed without merging**
