### PR TITLE
Enable filename option in print control

### LINKED ISSUE #1154: Print - Be able to set in config the name of the file that is created
**Is your feature request related to a problem? Please describe.**
As it is now the default name of the pdf or png that is created when printed is origo-map, it would be nice if that could be changed in the config for print control.

**Describe the solution you'd like**
In the config a alternative for name should be added.

### PR DESCRIPTION
**Pull request by johnnyblasta**
Fixes #1154

### CODE REVIEW

**Comment by MattiasSp** [comment]
Sweet! That was quick!

**Comment by tonnyandersson** [comment]
Works fine! However, I think it would make more sense if the variable was named `filename` throughout, instead of changing name to `name`. Or is there a reason for the name change?

**Comment by johnnyblasta** [comment]
> @johnnyblasta Works fine! However, I think it would make more sense if the variable was named `filename` throughout, instead of changing name to `name`. Or is there a reason for the name change?

The reason for having filename in the option was to avoid disambiguity about what name could refer to. Pure laziness that I didn't change the code that was already there for the rest.

**Comment by johnnyblasta** [comment]
Updated PR so that it consistently using filename for variable.

**Review by jokd — APPROVED** [review]

**Pull request merged**
