### PR TITLE
Addmarker

### LINKED ISSUE #1299: Add marker on map programmatically
**Is your feature request related to a problem? Please describe.**
It would be nice if it be possible to add a marker on the map with a popup from using the Origo.API.

**Describe the solution you'd like**
Via the Origo.API enter something like this:
`origo.api().addMarker([607355,6903985],'Test','Testing')`

To show a marker with popup like this:
image

### PR DESCRIPTION
**Pull request by johnnyblasta**
Closes #1299 

Makes it possible to show a marker via Origo API.

Example:
`origo.api().addMarker([1737367,8724008],'Test','Testing')`

### CODE REVIEW

**Comment by jokd** [comment]
Remove the console.log and you can merge this if you add it to the documentation asap. A nice option would be to be able to actually add an marker instead of an popup.

**Comment by jokd** [comment]
I did it so the tests can run

**Comment by johnnyblasta** [comment]
Ah, I looked for lints but it was not working, so I missed the console.log.

Actually this is some quick coding and thought someone would have some good ideas of improving it.

**Comment by jokd** [comment]
That can be future improvements

**Pull request merged**
