### PR TITLE
Adds created datetime label for print control

### LINKED ISSUE #916: Print - Date/time for creation
**Is your feature request related to a problem? Please describe.**
It would be nice to see the date/time for creation of printed map.

**Describe the solution you'd like**
The date/time for creation could be written out in the lower right corner. It should be selectable in the control settings if it is shown or not. Default value should be assigned in the config.

### PR DESCRIPTION
**Pull request by johnnyblasta**
Closes #916 

There is a fault I'm having trouble finding the cause for. First open the print control and deselect the "Använd marginaler". Then close the print control and open it again. The result is a white border at the bottom that shouldn't be there, see image.
image

### CODE REVIEW

**Comment by johnnyblasta** [comment]
The problem white border at the bottom is now fixed.

**Comment by tonnyandersson** [comment]
Perhaps this could have been made in a slightly cleaner way, without all the adding and removing of classes in print-component.js. Kinda like the margin, title and description controls. Would that require a lot of work?

**Comment by johnnyblasta** [comment]
Somewhat cleaner implementation is committed.

**Comment by tonnyandersson** [comment]
@johnnyblasta Oh, I forgot. The "Created..." text should be made into an option and should not be hardcoded.

**Comment by johnnyblasta** [comment]
Even cleaner implementation, but without same height on top and bottom margin when created is inserted. Removed an accidentally inserted multiple instance of description.

**Pull request merged**
