### PR TITLE
feature: add thematicStyling to sharemap

### PR DESCRIPTION
**Pull request by dahlalex**
Fixes [#issuenr 1951](https://github.com/origo-map/origo/issues/1951)

### CODE REVIEW

**Comment by johnnyblasta** [comment]
Tested and works fine for GeoJSON and WFS (I assume, from the code, didn't test that), but it don't work for WMS.

**Comment by johnnyblasta** [comment]
One thought:

- The config part would be more simple if the label was used instead of constructing an array with zeros and ones.

**Comment by johnnyblasta** [comment]
> I've made som changes to work also for WMS and found an issue that
> 
> ```js
> origo.api().getStyles()[styleName][0].thematic[index].visible = false
> ```
> 
> has no effect.
> 
> It seems that this issue should be solved even if the label is used (if i understand correctly).

ThematicStyling for WMS works by filtering the request, so I guess a new request has to be triggered.

**Comment by Grammostola** [comment]
It appears to work for WMS now, nice : ) However the link uses rule titles rather than rule names (whereas getLegendGraphic for instance is forced to use rule names). Rule names are ids and titles are for humans so I think it would be better if it the link was saved with rule names.

**Comment by Grammostola** [comment]
Cool, looks good now for WMS. For vector layers no themes are active when opening the shared map. I don't have an opinion on the separator, tilde is less common and this would likely do well described in the documentation somewhere too.

**Comment by Grammostola** [comment]
I used your example theme style for the origo cities layer and added an `id` prop to both. http://localhost:9966/#layers=osm/v/1/s/0/o/100,origo-mask/v/1/s/0/o/25,origo-cities/v/1/s/0/o/100/th/2&center=1810000,8390000&zoom=5.7&legend=expanded&map=index

...And the problem seems to be Number vs string. I gave the `id` prop a number value. Maybe both could be acceptable?

**Pull request merged**
