### PR TITLE
feature: filter on wms layer

### PR DESCRIPTION
**Pull request by johnnyblasta**
Example add on layer in config `"filter": "owner = 'me'"`

Closes: #1726

### CODE REVIEW

**Review by jokd — APPROVED** [review]

**Comment by jokd** [comment]
Looks good. I suppose sending in an undefined CQL_FILTER-param won't mess anything up.

**Comment by johnnyblasta** [comment]
> Looks good. I suppose sending in an undefined CQL_FILTER-param won't mess anything up.

If you don't specify a filter in config and sends a undefined CQL_FILTER Openlayers will handle it and not set a CQL_FILTER in the call to WMS server thereby it works as unfiltered.

**Comment by steff-o** [comment]
I have not had the time to check this thoroughly yet, but I think there can be some caveats here. AFAIK the cql_filter is a vendor specific parameter for Geoserver. If Qgisserver also has a CQL_filter parameter it should also be supported if it has a different name. The format of the filter may also differ, but that is no problem as the configuration will have to be adapted to the actual server anyway.

Also care must be taken when calling fetureinfo. I think the code uses the OL function _getFeatureInfoUrl_, which should copy all params from the WMS source. For geoserver this is not a problem as CQL_FILTER is also a valid parameter for the getFeatureInfo endpoint. But I think this must be verified.

**Comment by johnnyblasta** [comment]
Added support for QGIS Server which uses EXP_FILTER param instead of CQL_FILTER.
Haven't tested on QGIS Server.

**Comment by steff-o** [comment]
Another radical solution would be to just assign all incoming properties. In that way we support any vendor specific stuff, past, present and future but also loses all control.

**Comment by johnnyblasta** [comment]
Been reading more on QGISServer and it seems EXP_FILTER is only for WFS, might work with FILTER for WMS though.
Perhaps should test on QGISServer before merging.

**Comment by johnnyblasta** [comment]
> Another radical solution would be to just assign all incoming properties. In that way we support any vendor specific stuff, past, present and future but also loses all control.

QGIS Server seems to support quite a few extra params and counting the other systems extra params, so perhaps something to think about.

**Comment by filleg** [comment]
FILTER should work. The difference is that QGIS server wants layername included inside the FILTER parameter.

**Comment by johnnyblasta** [comment]
Changed to setting a params object which will be added to the calls.
More flexible, but demands more of the user knowing what to set.

Example filtering on Geoserver:
```
"sourceParams": {
            "CQL_FILTER": "pg_detaljtyp = 'parkering kvartersmark'"
}
```

Example filtering on QGIS Server (Works on Geoserver also):
```
"sourceParams": {
            "FILTER": "mylayer1:'col1';mylayer1,mylayer2:'col2' = 'blabla''"
}
```

Example setting multiple params on QGIS Server:
```
"sourceParams": {
            "DPI": "300",
            "BGCOLOR": "0x00FF00"
}
```

**Comment by filleg** [comment]
Tested the changes on qgis server and works with a kind of workaround I guess. The column value needs to be enclosed by double quotation marks which is a bit tricky in json. Solved it by using \" instead. Might not be obvious to users/administrators.

**Comment by jokd** [comment]
Then there isn't much to do but to merge this I'd say

**Pull request merged**
