### PR TITLE
ExternalUrl control in one commit

### PR DESCRIPTION
**Pull request by imantahriri**
This is a totally new branch out of Origo/master (version 2.0)

### CODE REVIEW

**Comment by imantahriri** [comment]
This PR solves issue #509. It takes the centre coordinate and sends it to an external map service (such as google maps or Blom Urbex).

The control is defined like this:

{
  "name": "externalurl",
  "options": {
       "tooltipText": "Kartlänkar",
       "links": [
           {
              "name": "google",
              "tooltipText": "Google maps",
              "method": "LatLon",
              "url": "https://www.google.com/maps/@?api=1&map_action=map&center={{LAT}},{{LON}}&zoom=18&basemap=terrain",
              "buttonImage": "img/png/google_maps.png"
            },
           {
              "name": "googlestreet",
              "tooltipText": "Google street view",
              "method": "LatLon",
              "url": "https://www.google.com/maps/@?api=1&map_action=pano&viewpoint={{LAT}},{{LON}}&heading=-45&pitch=10&fov=80",
              "buttonImage": "img/png/google_street_view.png"
            },
         ]
    }
}
The tool displays a button icon, pressing it will send you to the url. When configuring more than one link, the button expands and display an image for each url. If no button image is defined, a default image is displayed. It's possible to define projection and method (LatLon, XY).

externalurl_image

Perhaps this also solves issue #131 ?

**Comment by tonnyandersson** [comment]
Looks good!

Just a few remarks:

* There are still linter errors in the code
    * Newline missing at end of file(s)
    * A few unnecessary blank lines at top of blocks and some other places
    * Curly brackets missing in if-statement (externalurl.js)
    * Missing semicolon after import statements (externalurl.js)
    * Import order - absolute imports should come before relative imports. Hint - put OL imports first.
    * A few unused variables, especially in externalurlSeveralButtons.js
    * Two console.log() left behind in externalurlSingleButton.js

* Perhaps the image files (blom.png, google.png, mapillary.png) should be removed since this function is generic and not built specifically for the services mentioned. Just a thought.

**Comment by imantahriri** [comment]
Linter problems fixed.
PNG files removed.

**Comment by jokd** [comment]
Fallback of the tooltip perhaps shouldn't be 'Visa i BlomURBEX' but something more generic. Rephrase 'Visa kartan i en external platform'.
Besides that, it looks good and works well!

**Comment by imantahriri** [comment]
Fallback text fixed.

**Comment by jokd** [comment]
How about simply use the tooltip "Öppna i nytt fönster", since thats what it does? "Visa kartan i en external platform" can be misleading as well as a bit swenglish.
Besides that I think we can merge this.

**Comment by imantahriri** [comment]
I don't think "Öppna i nytt fönster" is a good indication of what it actually does. I would say "Visa kartan i en external platform" is much more accurate.

**Comment by tonnyandersson** [comment]
I agree with @imantahriri here. But as @jokd stated, the line should be rephrased to avoid mixing swedish and english. Try "Visa kartan i en extern plattform" or "Visa kartan i en extern karttjänst" instead.

**Comment by imantahriri** [comment]
Fixed now.

**Pull request merged**
