### PR TITLE
Fixes Outdated dependencies ISSUE #825

### PR DESCRIPTION
**Pull request by daRasmussen**
This PR would resolve outdated dependencies issues, it has been tested 2 times. Feel free to test and leave a comment.

### CODE REVIEW

**Comment by daRasmussen** [comment]
This PR NEEDS a update, since these changes would also update eslint rules and airbnb which leads to an update of code to match new lint standard. I suggest that these are fixed in an different issue/pr.

**Comment by daRasmussen** [comment]
This PR also fixes Issue #829

A config can be found [here](http://kartor.vasteras.se/sam/vas.json)

**Comment by jokd** [comment]
Everything seems to work well

**Comment by tonnyandersson** [comment]
LGTM2, @daRasmussen . But next time, please try to split the stuff into several PR's. I think it is bad practice to fix so many unrelated issues in the same PR.

**Comment by daRasmussen** [comment]
@tonnyandersson Yes, will do in the future!

**Pull request merged**
