### PR TITLE
Replaces jq carousel

### PR DESCRIPTION
**Pull request by daRasmussen**
replaces owl.carousel with glidejs, removes jquery dependency.

### CODE REVIEW

**Comment by jokd** [comment]
Will this eventually replace the owl carousel? How much is left to do (thinking about the upcoming release)?

**Comment by daRasmussen** [comment]
@jokd will commit more work later today.

**Comment by daRasmussen** [comment]
@jokd Check out the working draft.

**Comment by jokd** [comment]
Tested and works quite well. I noticed a couple of things though:
Popup/sidebar overflows when content is too big. Should be a scrollbar
When lots items are hit, the dots are on a long line instead of wrap in the popup.
Arrows and dots are sometimes rendered outside the popup.
image

Perhaps are all of these issues related and easily solved

**Comment by jokd** [comment]
Solves the issue where tha map stopped working in IE. However the carousel looks a bit funny and wont load more than one item.

**Comment by jokd** [comment]
One feature that is still lacking is the panning of the popup when rendered outside the map window. Besides that I think it is good to go.

**Pull request merged**
