### PR TITLE
Be able to put a style on Draganddrop control

### LINKED ISSUE #1134: Style DragAndDrop features
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to configure a style for the features in DragAndDrop control.

**Describe the solution you'd like**
A style object could be added in config with style rules for the features.

**Additional context**
Default style almost not visible feature:
image

Same feature with a config style:
image

### PR DESCRIPTION
**Pull request by johnnyblasta**
Closes #1134

### CODE REVIEW

**Comment by daRasmussen** [comment]
@johnnyblasta Very nice!

**Comment by tonnyandersson** [comment]
@johnnyblasta Could this be made to work like [selectionStyles](https://github.com/origo-map/origo-documentation/blob/master/content/settings.md#example-featureinfooptions-with-overlay-as-infowindow), with individual styles for each geometry type? For example, if I want to use different stroke styles for lines and polygons. Now it seems like there's only one stroke style to rule them all.

**Comment by johnnyblasta** [comment]
> @johnnyblasta Could this be made to work like [selectionStyles](https://github.com/origo-map/origo-documentation/blob/master/content/settings.md#example-featureinfooptions-with-overlay-as-infowindow), with individual styles for each geometry type? For example, if I want to use different stroke styles for lines and polygons. Now it seems like there's only one stroke style to rule them all.

Thought this was a simple and neat solution. Points gets a different style anyway. 
Don't have any good use cases, but some might want to be able to style their features on the fly also. Would be cool to also drop a style at the same time.

**Comment by jokd** [comment]
I understand Tonnys opinion. It is also a bit confusing that we style stuff different ways in the config, perhaps we should try to unify the methods/syntax.

**Comment by johnnyblasta** [comment]
Updated the style syntax to same as selectionStyles in featureinfo.
Also added new style type GeometryCollection which can be used by GeoJSON.

**Review by jokd — APPROVED** [review]

**Pull request merged**
