### PR TITLE
Modal iframe

### LINKED ISSUE #381: Full screen modal with iframe
It would be nice to be able to open links as iframes inside a modal, preferably full screen.
We have been using colorbox but it would be better with something in the Origo core.
Thoughts on this?

### PR DESCRIPTION
**Pull request by jokd**
Fixes #381 
Add target: modal or modal-full to open links in modal window instead of a new window. Used along with url. 
Example:

```
{
  "name": "name",
  "url": "url",
  "target": "modal-full"
}
```

### CODE REVIEW

**Comment by mulfvik** [comment]
Looks good, I close #774 #775.
If use config like this 
`{
  "url": "url",
  "html": "Läs mer &raquo; ",
  "target": "modal-full"
}`
the html value is showing in the modal top but it migth be nice if it always shows the url?

**Comment by jokd** [comment]
@mulfvik Im sure there are cases where you want this behaviour but also the opposite. I guess we can make it configurable.

**Comment by jokd** [comment]
@mulfvik Please have another look

**Comment by mulfvik** [comment]
Lookin good @jokd

**Pull request merged**
