### PR TITLE
OL 5.3.0

### LINKED ISSUE #474: Upgrade to OL5
I have started on a branch and made the necessary changes to get Origo running with OL5:
https://github.com/origo-map/origo/tree/OL5

### PR DESCRIPTION
**Pull request by jokd**
Fixes #474

### CODE REVIEW

**Comment by markus659** [comment]
Have you tried if 
```js
import Map from 'ol/Map';
```
would work instead of

```js
import Map from 'ol/map';
```
in the viewer? That's one example OL give in their upgrade notes to 5.x https://github.com/openlayers/openlayers/wiki/OpenLayers-v5.x

It'd be nice if we could be consistent with how we write the imports.

**Comment by jokd** [comment]
@markus659 You are correct, that is the way we should do it. There are lots of changes that needs to be made, I have just fixed the warnings. However, as long as we are consistent we won't get any warnings even if we use the wrong casing.  So there's obviously some work to be done.

**Comment by jokd** [comment]
Now I think we are good to go. Haven't tested in an AGS-environment though. Please have a look @markus659 @tonnyandersson  @afogelberg

**Comment by tonnyandersson** [comment]
Seems to work as expected in AGS-environment.

**Comment by jokd** [comment]
OK to merge this?

**Comment by markus659** [comment]
Maybe we should remove the caret from the openlayers line in the package file, so that it uses a fixed version?

**Comment by jokd** [comment]
@markus659 Sure, can't see why we shouldn't

**Comment by daRasmussen** [comment]
Very Nice!

**Pull request merged**
