### PR TITLE
Fixes #127, layer transparency

### LINKED ISSUE #127: Set transparency on layer
Option for user to set transparency on layer.

### PR DESCRIPTION
**Pull request by jokd**
Idea for solving #127, adds a slider in the layer tab. No configuration at this moment so it is shown for every layer.
image

### CODE REVIEW

**Comment by tonnyandersson** [comment]
Perfect! But it should definitely be a layer setting, like `"transparenceControl": true`.

And **PLEASE** - for the love of \*insert deity of personal preference\* - give it some Origo-esque CSS love!

**Comment by jokd** [comment]
@tonnyandersson Please elaborate your criticism. The native slider is beautiful in its simplicity. It even works on touch screens sometimes.

**Comment by tonnyandersson** [comment]
If it works on touch screens _sometimes_ - I'm convinced! Just give it a splash of the OrigoBlu&trade; and it's good to go!

All jokes aside, I was thinking about something along these lines (pun very much intended):

image

**Comment by jokd** [comment]
@tonnyandersson What should be the default behaviour? I vote for true.
OK with this: ?
image

**Comment by jokd** [comment]
set opacityControl: false on a layer to deactivate the slider

**Comment by tonnyandersson** [comment]
@jokd Personally, I think it would look better without the bar shadow, like in the example. I also think it looks cleaner if it is deactivated by default, but then most people won't use the feature because they won't know it exists.

So, drop the bar shadow (but keep the button shadow) and make it activated by default. My two cents.

**Comment by jokd** [comment]
@tonnyandersson I dropped the box-shadow:
image

**Comment by tonnyandersson** [comment]
Three thumbs up regarding the looks! Haven't tested it yet, though, but it looks great.

**Comment by tonnyandersson** [comment]
Works fine in Chrome and Edge, but not in IE11 (surprise!). Input event is not triggered. Other than that, it's good to go.

**Comment by jokd** [comment]
@tonnyandersson Haven´t we dropped support for IE11?

**Comment by tonnyandersson** [comment]
@jokd I guess. Feels weird, though. Your call if you wanna try and fix it. I'll approve this.

**Comment by jokd** [comment]
@tonnyandersson I suppose you will have to listen to _change_ event rather than _input_ to make it work in IE11. This will require either an IE exception or a change in behaviour where you must release the slider to trigger the event.

**Pull request merged**
