### PR TITLE
Changes needed for draw plugin

### LINKED ISSUE #608: Changes needed to accomodate draw plugin
Some changes need to be made in the core for the draw plugin to work properly:

- Expose style and featurelayer modules
- Add setStyle() function to featurelayer.js
- Add fa-map-marker to fa-icons.svg

### PR DESCRIPTION
**Pull request by tonnyandersson**
Fixes #608

### CODE REVIEW

**Comment by daRasmussen** [comment]
@tonnyandersson nice! Could you supply a config, for test?

**Comment by tonnyandersson** [comment]
You would have to install the [draw plugin](https://github.com/origo-map/draw-plugin/tree/pull-request) to actually test these additions. I guess the most important thing is to verify that these changes does not break Origo in any way.

**Comment by daRasmussen** [comment]
So this PR is dead?

**Comment by tonnyandersson** [comment]
No, what makes you think it's dead?

**Pull request merged**
