### PR TITLE
IE not like includes

### PR DESCRIPTION
**Pull request by mulfvik**
This fixes the issue #939 but there are still errors. This doesnt add too much code and awaits no Origo support for IE

### CODE REVIEW

**Comment by tonnyandersson** [comment]
Isn't there a polyfill for `includes`?

https://github.com/origo-map/origo/blob/master/src/utils/polyfill.js

**Comment by mulfvik** [comment]
When importing babel/polyfill in polyfill.js its fine. I dont know if its supposed to be imported this way though?

**Comment by jokd** [comment]
We need polyfill for custom events as well

**Comment by jokd** [comment]
Nevermind, polyfill was overkill. I pushed a minor fix.

**Pull request merged**
