### PR TITLE
Rotation disable

### PR DESCRIPTION
**Pull request by mulfvik**
Proposal for disabling rotation, issue #379

### CODE REVIEW

**Comment by tonnyandersson** [comment]
@mulfvik There's an easier way to disable rotation: https://github.com/origo-map/api-documentation/blob/master/content/settings.md#enablerotation

I get what you are after, though. But I think removing a control from origoConfig.js is only supposed to remove the physical control - i.e. buttons and stuff - not removing the interaction connected to the control. Take a look at the zoom control, for instance. This makes it possible to get a cleaner UI while maintaining funtionality.

If we want to be able to remove the functionality together with the physical control, I think this should be done in a more generic way, applicable to all relevant controls and interactions. And perhaps it could be done outside of viewer.js.

But that's just my opinion.

**Comment by mulfvik** [comment]
@tonnyandersson Ah, did'nt get that setting. Time to reread the docs. Thanks Tonny :) Maybe zoom and attribution controls are the exeptions in this case. This should be handled in another issue i guess. Closing this one.

**Comment by afogelberg** [comment]
Also note that you don't have to use the default controls. To remove the default controls you can do this:
```javascript
var map = origo.map.init('test.json', {
    defaultControls: []
});
```

**Comment by mulfvik** [comment]
@afogelberg Its so obvious when you show it :) Cheers Anders

**Pull request closed without merging**
