### PR TITLE
ExternalUrl control

### PR DESCRIPTION
**Pull request by imantahriri**
All changes for the externalUrl control in one commit.

### CODE REVIEW

**Comment by asemoller** [comment]
This PR solves issue #509. It takes the centre coordinate and sends it to an external map service (such as google maps or Blom Urbex).

The control is defined like this:
```
{
  "name": "externalurl",
  "options": {
       "tooltipText": "Kartlänkar",
       "links": [
           {
              "name": "google",
              "tooltipText": "Google maps",
              "method": "LatLon",
              "url": "https://www.google.com/maps/@?api=1&map_action=map&center={{LAT}},{{LON}}&zoom=18&basemap=terrain",
              "buttonImage": "img/png/google_maps.png"
            },
           {
              "name": "googlestreet",
              "tooltipText": "Google street view",
              "method": "LatLon",
              "url": "https://www.google.com/maps/@?api=1&map_action=pano&viewpoint={{LAT}},{{LON}}&heading=-45&pitch=10&fov=80",
              "buttonImage": "img/png/google_street_view.png"
            },
         ]
    }
}
```
The tool displays a button icon, pressing it will send you to the url. When configuring more than one link, the button expands and display an image for each url. If no button image is defined, a default image is displayed. It's possible to define projection and method (LatLon, XY). 

externalurl_image

Perhaps this also solves issue #131 ?

**Comment by jokd** [comment]
There are Linter errors in the code.
Perhaps the elements should be positioned in the misc-toolbar instead of a new one?
If the js files needs to be separated I suggest we move externalurlSingleButton and externalurlSeveralButtons to an externalurl-folder instead of ./controls
Code needs to be refurbished to Origo 2.0

**Comment by jokd** [comment]
With Origo 2.0 in my previous comment I meant the control should be written as the controls are since Origo 2.0; with the use of ES6, avoiding jQuery and using the ui-component system.

**Comment by imantahriri** [comment]
I am closing this PR because it no longer valid. 
I have created a new PR out of a fresh copy of origo/master after realesing version 2.0

**Pull request closed without merging**
