### PR TITLE
Show attribute as title

### LINKED ISSUE #449: Show attribute as title
It would be nice to be able to configure a layer to show an attribute in the titlebar of a popup/sidebar instead og the layername.

### PR DESCRIPTION
**Pull request by jokd**
Fixes #449
Adds a titleAttribute option for layers to show a attribute value instead of the layer name as the title in the popup/sidebar.

### CODE REVIEW

**Comment by afogelberg** [comment]
Good idea @markus659 . I was thinking the same.

**Comment by jokd** [comment]
Of course, will fix that!

**Comment by jokd** [comment]
...though you typically dont wanna have a dynamic title for the layer as suggested, right? In the mapmenu for example. @markus659 @afogelberg

**Comment by markus659** [comment]
Yeah, you're right, that wouldn't work. Maybe declare as such when you want to use an attribute as title:

```json

        "title": [{
          "layer": "Origokommuner",
          "featureinfo": "{{name}}" 
        }]
```

If not, you do it the way it works currently:

```json
       "title": "Origokommuner",
```
Not sure if it's better than the original suggestion.

**Comment by tonnyandersson** [comment]
@jokd @markus659, perhaps a little bit of both? Go with the original suggestion but change the property name from _titleAttribute_ to _featureinfoTitle_ or _popupTitle_ or something, just to avoid ambiguity.

**Comment by jokd** [comment]
I vote for just renaming the attribute to featureinfoTitle (since it also applies on the sidebar). Fix is pushed. 
Also use replacer utility and fall back on layer title / name.

**Comment by jokd** [comment]
Can we merge this? Would be a nice addition for a project of mine.

**Pull request merged**
