### PR TITLE
Falls back on default style instead of throwing error

### LINKED ISSUE #166: Provide default style
If style is not provided for a layer a default style should be used

### PR DESCRIPTION
**Pull request by jokd**
Fixes #166 and replaces #501

### CODE REVIEW

**Comment by tonnyandersson** [comment]
Works well, mostly, but is seems the default point style is not being respected. According to the default style function, Point and MultiPoint layers should be rendered with yellow fill and stroke but are rendered in black.

**Comment by jokd** [comment]
Yeah, the function shouldnt create the style before the fill is set. That is perhaps another issue.

**Comment by tonnyandersson** [comment]
Yeah, perhaps you're right. Another thing, though. The legend is not picking up on the default styles. I'm guessing that's because the legend gets the layer style definitions from the config file. Different (and slightly bigger) issue, but something that needs to be addressed for this to work as intented.

Other than _that_, this PR seems fine.

**Comment by jokd** [comment]
Agreed thats quite a job. A simple solution meanwhile could be to show a generic icon when using a stylefunction. Can we merge this anyway and form an issue for the stuff thats left?

**Comment by tonnyandersson** [comment]
I'm cool with that.

**Pull request merged**
