### PR TITLE
Fix when pagesettings is not set

### PR DESCRIPTION
**Pull request by jokd**
Fixes bug introduced in #1254 where the map crashes unless pageSettings is set in the config.

### CODE REVIEW

**Comment by johnnyblasta** [comment]
The shut off stops working by this fix, so there has to be made some code changes.

Change in mapinteractions.js 
```
const MapInteractions = function MapInteractions(options = {}) {
  let mapInteractions = { embedded: true };
  if (Object.keys(options.mapInteractions).length !== 0) {
    mapInteractions = options.mapInteractions;
  }
  if (isEmbedded(`#${options.target}`) && mapInteractions.embedded) {
```

Change in print-interaction-toggle.js 
```
export default function PrintInteractionToggle(options = {}) {
  const {
    map,
    target,
    toggleIcon = '#ic_map_24px',
    mapInteractionsActive
  } = options;
  const interactions = mapInteractions({ target, mapInteractions: map.getView().options_.pageSettings ? map.getView().options_.pageSettings.mapInteractions : {} });
  let mapInteractionToggleButton;
```

**Comment by johnnyblasta** [comment]
Still a case when it fails. When pageSettings is set but not mapInteractions, so here is new code:

In map.js
```
const Map = (options = {}) => {
  const interactions = mapInteractions({ target: options.target, mapInteractions: options.pageSettings && options.pageSettings.mapInteractions ? options.pageSettings.mapInteractions : {} });
  const mapOptions = Object.assign(options, { interactions });
```

In print-interaction-toggle.js
```
  } = options;

  const interactions = mapInteractions({ target, mapInteractions: map.getView().options_.pageSettings && map.getView().options_.pageSettings.mapInteractions ? map.getView().options_.pageSettings.mapInteractions : {} });
  let mapInteractionToggleButton;
```

You didn't mentioned and fixed the "dangling" lint that this introduced?

**Comment by jokd** [comment]
I just pasted your lines. Its probably better if you push your fixes to this branch.

**Comment by johnnyblasta** [comment]
> I just pasted your lines. Its probably better if you push your fixes to this branch.

Nah, then I have to figure out how to checkout that branch ;)

**Comment by johnnyblasta** [comment]
Made the changes here on Github.
Didn't fix the lint, since I don't know what to do about it.

**Comment by jokd** [comment]
@johnnyblasta Please have another look

**Review by johnnyblasta — APPROVED** [review]
Now it works for the test cases I can come up with, when I fixed a small typo.
LGTM

**Pull request merged**
