### PR TITLE
Replaced setview and setzoom in geoposition

### LINKED ISSUE #231: Add animation to geoposition
Requires that we update ol, see #116 .

### PR DESCRIPTION
**Pull request by markus659**
This one-liner fixes #231. Not too much to it really, but I would appreciate an extra look at it just in case as I'm not completely sure what the issue is referring to.

### CODE REVIEW

**Comment by afogelberg** [comment]
Thanks for working on this @markus659 . Initially I thought the animation shouldn't be chained, but after some testning I think it's more clear to chain it like you have done.

One remark only, I think it would be good to change how the zoom level is set, since we don't know the resolutions in different implementations of Origo. Maybe we can calculate the zoom level from the max resolution, for example max resolution - 3? And just to be safe, also have the zoom level as an option.

**Comment by markus659** [comment]
Thanks for the feedback @afogelberg. I wasn't too sure about the chaining either, I would prefer if the animations started simultaneously (not sure if this is possible or how you would go about implementing it). I think the chaining works fine though. I agree with your other comments, I made changes accordingly in the latest commit. Now it is possible to set zoomLevel as an option for the geoposition control, like so:

```json
    {
      "name": "geoposition",
      "options": {
        "zoomLevel": 15
      }
    }
```
This will result in the animation zooming to the specified level,  if the zoom level is not specified it will be calculated from the resolutions.

**Comment by afogelberg** [comment]
If you don't want chaining you can do it like this:
```
 map.getView().animate({
   center: position,
   resolution: (viewer.getResolutions().length - 3)}
});
```

**Comment by markus659** [comment]
That was easy enough :-).  I prefer it without the chaining, but either works for me. Which one should we go with?

**Comment by afogelberg** [comment]
> I prefer it without the chaining

Agreed :)

**Pull request merged**
