### PR TITLE
Fixed position on coordinates

### LINKED ISSUE #914: Position controll performance issue
**Describe the bug**
Position controll in latest origo-master update coordinates when panning map, browser need to render more resulting in lag/stutter. The issue is also somehow related to the legend controll and how many layers/group/subgroup it contains so if you have a lot of them it the map it will adversely affects performance.

**To Reproduce**
1. Add more (>10 of each) layers/groups and subgroups to index.json example.
2. Click and pan/drag the map (see that coordinate update in footer when pan).
3. Test panning the map using legend controll on or off to see the difference.
4. Recording performance in chrome debug shows renderingtime for task ”layout” that is higher even if layers are turned off.

**Expected behavior**
Working in same way as in origo version 1 when coordinates from mousepointer locks and not update when you click/hold and drag/pan the map.
Alternative (or both solutions) have a option for position controll to only use positonmarker (sight icon) function and not the ”always on” mousepointer update coordinates.
Of course best solution should be to solve the core problem, why legend items affects performance in Origo version 2.x.x

**Desktop (please complete the following information):**
 - OS: WIN10 build 18362
 - Browser chrome
 - Version 81

### LINKED ISSUE #955: Background maps abstract flutter
Background maps abstract flutter

`"attribution": "&copy Lantmäteriet Geodatasamverkan | Strängnäs kommun",
      "abstract": "<p>Information om när detta fotot är taget finner du <a href='https://geolex.etjanster.lantmateriet.se/?e=614815&n=6580926&z=7&profile=default_geolex_orto_latest_year_noauth' target='_blank'>här</a> på Lantmäteriets tjänst GeoLex.</p>"`

captured

### LINKED ISSUE #956: Background maps abstract does not handle a tag properly
Can not follow link with click in background map abstract. Maybe it is due to z-index?

### PR DESCRIPTION
**Pull request by mulfvik**
Fixes #955
Fixes #956
Fixes #914

### CODE REVIEW

**Comment by tonnyandersson** [comment]
Looks good at first glance. But! If you add the scalepicker control _after_ the position control, the scalepicker control will cover the mouse coordinates.

flutter

Also, the texts are not perfectly aligned. But you already know that.
image

**Comment by jaha7** [comment]
The issue @tonnyandersson mention also appear using the "old" scalecontroll
origo_postition_probs

**Comment by tonnyandersson** [comment]
@jaha7 Unable to reproduce. What browser are you using?

scalepicker

**Comment by mulfvik** [comment]
Its dependent by in what order you call the controls so this shouldnt be dependent of config order i guess
captured

**Comment by jaha7** [comment]
tested "old" [scale-control](origo-map.github.io/origo-documentation/latest/#scale-control) with Chrome, Edge (chromium) and Firefox, same results
in previous example we have temporary disabled "always on" because our performance issue with #914 

new example, position-control first
origo_postition_probs2

new example,  scale-control first
origo_postition_probs3

**Comment by mulfvik** [comment]
I know this has been up for discussion before and we chose the alternative that scalepicker could render both before and after position control.
Now I think it looks a bit weird when scale controls is pushed aside when mouseposition coordinates is activated.
Any other thoughts on this?

**Comment by tonnyandersson** [comment]
@jaha7 Sorry, my bad. My mind went straight to the newer scale _picker_ control. You are right, though. The fixed coordinates will cover the old scale control (or the other way around).

@mulfvik With the scale _picker_ control, I had the ambition to make it so it could be placed pretty much anywhere, in any toolbox. I totally agree with the weirdness of scale controls being pushed aside, though. But I also like the idea of having a high level of freedom...

However, we can't allow controls to be placed on top of each other. So, in my opinion, either we make _all_ footer controls fixed in some way, or none.

**Comment by mulfvik** [comment]
Like the part about freedom, reminds me of Mel Gibson in Braveheart. Ill dig in to this and see what comes up.

**Comment by jaha7** [comment]
@tonnyandersson Alright, no probs, we like the scalepicker and in my opinion the "old" scale-control is not needed because of scalepicker-control (if neccecary with option that disable droplist for those usercases)

maybe coordinates could show last in "footer-controls" row regardless of scalepicker (or other control being in between)?

**Comment by mulfvik** [comment]
@jaha7 that sounds like the prettiest alt. so far.

Also, coordinates only show if screensize width >1158px

**Comment by mulfvik** [comment]
Tested some more and suggestion to let position render last and override control init order sounds good for me.
What do you think @tonnyandersson ?
captured

**Comment by jaha7** [comment]
Clarification of the suggestion i mention, i undertand this can be more tricky.

Screenshot example fixed in paint :)  (scalepicker after position, new placeholder after last control)
paint

Another suggestion, coords in same box, text for no coords needed.
paint2

**Comment by tonnyandersson** [comment]
@mulfvik I'm kinda into the whole "freedom" thing... Also, the position control looks best when positioned first in the footer.

@jaha7 Two really nice options. The first option doesn't feel 100% intuitive, though, since the coordinates are a part of the position control, with the crosshair and projection changing functionality and all. I think it works best if they are kept together.

Which is why I like the second option more. Perhaps it will look weird if the coordinates are hidden when the mouse pointer is outside the map, but it will probably not look any weirder than the current sidestepping scale controls. We could probably let the coordinates show as well, even when the mouse pointer is outside the map, by "freezing" the last coordinates shown before mouseOut.

**Comment by tonnyandersson** [comment]
@mulfvik After some diggin', I found a solution that seems to fix the fluttering legend issue, without touching the position control. Just change `overflow-y` to `scroll` in the `contentStyle` parameter on row 96 of src/controls/legend/overlays.js:

https://github.com/origo-map/origo/blob/6e738bbc51305ae4d5690922d0691f622c3e0747/src/controls/legend/overlays.js#L90-L101

This fixes the fluttering issue, but I'm not 100% certain it won't break anything else. Poked around for a bit but couldn't find anything leaking. It won't fix the sidestepping scale controls issue, though. but neither #955 nor #956 is about that anyway. So...

**Comment by mulfvik** [comment]
Nice one @tonnyandersson . I think im on to fixing the position. Else lets go for your solution.

**Comment by mulfvik** [comment]
Went with @tonnyandersson flutter fix. Then added option to define text or freeze coordinates at last position.
`{
      "name": "position",
      "options": {
        "noPositionText": "No position access"
      }
 },`
If `"noPositionText": ""` last coordinates show.

**Comment by jaha7** [comment]
Nice work, tested and for me its working fine.

There's just one more thing... :)
When click/hold "pandrag" the map, coordinates jumping around. 
coords_origo
In Origo v1 the coordinates locks.

#914 can also be closed after this PR

**Comment by tonnyandersson** [comment]
@mulfvik You know what? I don't like my flutter fix anymore. Sure, it fixes the fluttering, but it looks like crap in IE, for example, since the scrollbar is permanently visible when using `overflow-y: scroll`:

image

Looks better in Chrome, but you can see the "empty" space set aside for the scrollbar:

image

Sadly, I don't have any better ideas right now.

**Comment by mulfvik** [comment]
@jaha7 Check out Jumping coordinates commit if it solves it.

**Comment by mulfvik** [comment]
@tonnyandersson Ok, back to it then :)

**Comment by jaha7** [comment]
@mulfvik Very nice, It solves the problem and the PR works really well for me overal because legend not affecting rendering time when zooming and panning.

Though there is one CSS bug left that i see.
css_p

**Comment by mulfvik** [comment]
@tonnyandersson I can live with the scrollbar design in IE. The usage of IE is so low at this point.

**Comment by mulfvik** [comment]
@jaha7 I think the footer should be closed if not all the controls fit. Or maybee in this case if position control and scalepicker or scale control fit. Otherwise its hard for the user to know why

@tonnyandersson Looking for media querys variables but cant find any, i.e. `$media-l`. Do you know where they are located? Part of a library that is being called from somewhere in the void?

**Comment by jaha7** [comment]
@mulfvik I agree, sounds like a good solution. Test using width 40%,20%,40% (left, center, right footer content) also give some more space for footer-controls from the left.

**Comment by mulfvik** [comment]
@tonnyandersson Can you have a look at latest commit please. Might be ready for merge...

**Comment by tonnyandersson** [comment]
@mulfvik Nope, still got the flutters.

Here's my final suggestion: change class `flex` to `inline-block` on the main legend element. This will probably screw up something else, but I can't see any negative changes my self.

**Comment by mulfvik** [comment]
@tonnyandersson  Weird, could have been the cache even though...
 Cant either see any negativ consequences, good job!

**Comment by tonnyandersson** [comment]
Good work, @mulfvik! Just remember to add a few lines about the `noPositionText` option in the documentation.

**Pull request merged**
