### PR TITLE
imageresizer, Fixes issue #628

### LINKED ISSUE #628: Image resizing not working properly in the editor
Images seems to get enlarged rather than scaled to fit the editor window

### PR DESCRIPTION
**Pull request by jokd**
Fixes issue with rotation and formats other than jpeg.

### CODE REVIEW

**Comment by tonnyandersson** [comment]
@jokd Can you provide an example config for testing?

**Comment by jokd** [comment]
I have no public service with image fields but simply turn off autoSave and set a field to "type": "image". Create a new feature and attach an image, close and reopen the attribute window. 
Before this PR the image was often rescaled or invalid but now it's simply perfect.

**Comment by tonnyandersson** [comment]
Getting errors when adding images (see image below), but I guess that's a different issue. The resizing seems to work just fine. Or "simply perfect", as you put it. :)

**Comment by jokd** [comment]
@tonnyandersson I can’t see your screenshot but if you think it has nothing to do with the original issue I’ll merge this.

**Pull request merged**
