### PR TITLE
feature: draw-plugin as core control

### LINKED ISSUE #1610: Adding draw to core
**Is your feature request related to a problem? Please describe.**
The draw plugin is widely used and should be in the origo core. Adding it won't be many kB extra to the build and it will be the first step in solving #1609.

### PR DESCRIPTION
**Pull request by jokd**
Fixes #1610 
Adding draw to core will ease the job in unifying measure, draw and editor ( #1609 )

### CODE REVIEW

**Comment by jokd** [comment]
@Grammostola Fixed the issue and added the changes in https://github.com/origo-map/draw-plugin/pull/64

**Comment by Grammostola** [comment]
Hello,

Looks better : ) 

The features look good when 300dpi is selected in the print preview and I see no console errors anymore. Sharemap via mapstate works as with the plugin i.e well from what I can tell.

The one thing still missing are the submenus for line and polygon (rectangle, freehand etc).

**Comment by jokd** [comment]
You have to add them, eg:
{
      "name": "draw",
      "options" : {
        "buttonText": "Rita krita",
    "drawTools": {
      "Polygon": ["box"]
    }
      }
    }

Default there are none

**Comment by Grammostola** [comment]
Right you are. Looks good to me then.

**Review by Grammostola — APPROVED** [review]

**Comment by steff-o** [comment]
"It would be nice" if #1467 were considered if implementing export to file of drawn objects.

**Comment by jokd** [comment]
Replaced with #1714

**Pull request closed without merging**
