### PR TITLE
Update set-scale-control.js

### LINKED ISSUE #1182: Print - Set default scale
**Describe the bug**
You are not able to set the resolution of the print unless the scale is set (which it isn't initially). Therefor it makes sense to default the scale to something when activating the print control, eg the one closest to the present map.

**To Reproduce**
1. Open print
2. Try to change resolution

**Expected behavior**
Change resolution without picking scale first.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version 88

### PR DESCRIPTION
**Pull request by jokd**
Sets default scale to ~same resolution as the map
Fixes #1182

### CODE REVIEW

**Comment by tonnyandersson** [comment]
Setting the default scale seems to work fine. But I noticed that the print scale picker doesn't change when zooming in the print preview map. Is this a bug or a feature?

Please note that this issue is present in the master branch as well.

print_zoom_scale

**Comment by johnnyblasta** [comment]
> Setting the default scale seems to work fine. But I noticed that the print scale picker doesn't change when zooming in the print preview map. Is this a bug or a feature?
> 
> Please note that this issue is present in the master branch as well.
> 
> print_zoom_scale

Something to consider when implementing that is the case when the zoom levels in the map and those defined in the print control doesn't match. What should be shown in scale picker then?

**Comment by jokd** [comment]
That’s another issue I’d say. This is just to get the resolution picker working without having to select scale first. 
Like Johnny says, there are things to consider when changing behavior of the scale picker.

**Comment by jokd** [comment]
So yeah it’s a feature^^

**Comment by tonnyandersson** [comment]
Fair enough.

But there's a big boo-boo right around line 62:

image

**Comment by jokd** [comment]
I shouldn’t have edited in word.

**Comment by tonnyandersson** [comment]
LOL! Word... You should use Notepad instead. Superior tool, so much better.

**Comment by jokd** [comment]
Just kidding, stole it from SO.
Notepad is great though.

**Comment by tonnyandersson** [comment]
Found a tiny, tiny issue. To replicate:

1. Load the map and zoom to a scale of your liking, let's call it Scale A
2. Open the print control and open the settings tab, the scale picker now shows Scale A (or closest available)
3. Now close the print control and zoom to a completely different scale, henceforth called Scale B
4. Open the print control once again and gasp at the horrific fact that the scale picker still shows Scale A

Bug or feature?

**Comment by jokd** [comment]
Clearly a bug, will look into it next week

**Comment by jokd** [comment]
There are still a bit funny behaviour when using the high and low dpi settings because when changing the resolution in the print settings you are actually zooming in or out in the map while scaling the print. When the print window is closed, the map has zoomed in (when using 300dpi) or out (when using 75dpi). If then activating print mode again, the map has stepped 1 zoom level in or out. 
This is however another issue.

**Comment by tonnyandersson** [comment]
...aaand now the map scale doesn't match the scale picker scale:

image

**Comment by jokd** [comment]
Yes it does unless you zoom ( or pan in a web mercator map). The scale is not updating as mentioned earlier in this thread

**Comment by jokd** [comment]
You are far up north. around Berlins latitude it works great.
Jokes aside, constrainresolution will have this effect, especially when using web mercator.

**Review by tonnyandersson — APPROVED** [review]

**Comment by jokd** [comment]
Agree but at least it works well when constrainResolution is false and using sweref.
Havent tested when setting scale in the print settings config though....

**Pull request merged**
