### PR TITLE
updates agsTransaction

### LINKED ISSUE #455: agstransaction url
The url in agstransaction could be fixed.

### PR DESCRIPTION
**Pull request by daRasmussen**
Fixes #455

### CODE REVIEW

**Comment by daRasmussen** [comment]
This is basically what this PR does. 

agsTranscationTEST

**Comment by daRasmussen** [comment]
Yepp my point is...

**Comment by tonnyandersson** [comment]
Your point is...?

**Comment by daRasmussen** [comment]
@tonnyandersson could you give an example? The slice function is not applied to **ID** its applied to **URL**.

**Comment by tonnyandersson** [comment]
Yes, that's exactly what I mean. Id's are not always strings, and the integer datatype does not have the slice function.

Btw, do we have a policy regarding template literals vs toString()? I'm okay with both, just asking for future reference.

**Comment by tonnyandersson** [comment]
LGTM

**Comment by daRasmussen** [comment]
I would say that it depends on the context and that it is better to be consistent and avoid mixing and in general literals delivers better performance than functions.

**Pull request merged**
