### PR TITLE
feature: thematic styling

### LINKED ISSUE #1629: Hide features when thematic style
**Is your feature request related to a problem? Please describe.**
It would been nice to be able to hide some of the features in a thematic style.

**Describe the solution you'd like**
On a thematic style there could be a checkbox in front of each style and if you want to hide a certain type you just uncheck the box and the features disappears from the map.
image

**Describe alternatives you've considered**
The function should perhaps be off by default and can be activated on a layer level.

### PR DESCRIPTION
**Pull request by jokd**
Fixes #1629
"thematicStyling": true as a layer option will enable this feature. Works hopefully with both vector and wms services. However, using stylePicker will override this setting for now.

### CODE REVIEW

**Comment by Grammostola** [comment]
Very nice!! 
A couple of observers:
- What Johnny said, the remaining wms bits disappear upon changing zoom level
- I can't click the radio buttons inside the info / legend pane of the layer
- ( What classes are active in the layer isn't saved to a mapstate)
- ( What classes are active in the layer isn't understood by the Print module)

**Comment by jokd** [comment]
> Very nice!! A couple of observers:
> 
> * What Johnny said, the remaining wms bits disappear upon changing zoom level
> * I can't click the radio buttons inside the info / legend pane of the layer
> * ( What classes are active in the layer isn't saved to a mapstate)
> * ( What classes are active in the layer isn't understood by the Print module)
> * ( (  (
> 
> ```json
>       "thematicStyling": true,
>       "hasThemeLegend": true
> ```
> 
> looks a little funny but it doesn't break anything. Logically `thematicStyling` isn't relevant if not `hasThemeLegend`. Perhaps `selectiveThemes` or something in stead of `thematicStyling`? ) ) )

The wms issue should be solved now. Apparently you can't send in an empty filter.
The radio buttons on the overlay properties are intentionally not clickable since that would require some new logic to handle the synchronizing of the different legends. Therefore you have the default cursor and not the pointer.
Haven't looked into mapstate but that will complicate the permalink handling quite a bit but if someone wants it it is definitely up for grabs.
I can probably fix the print legend quite easy.

Cheers!

**Comment by Grammostola** [comment]
The WMS image lingering appears fixed. 
The radio buttons on the overlay props - ah, I see. Perhaps less obvious on a mobile platform? I don't suppose they can easily be removed there?
Sharing, hmm, I guess we would need the index of the turned on classes of the `thematic` array of a layer's style with a `thematicStyling` (that is also active) (and where at least one class is turned off, ie filter in effect). In theory we might `encodeURIComponent(aJSON.stringifiedArrayOfIndexNumbers)`

**Review by johnnyblasta — APPROVED** [review]
Great stuff!
The sharing would be a plus to have, but see no problem to let this in as is and deal with that later if needed.
When having a featureinfo popup and click on hidding the style for the feature, the popup is still visible. Not nescerraly something that should be fixed either before merge.

**Comment by jokd** [comment]
I merge this and your comments can be enhancements for the future

**Pull request merged**
