### PR TITLE
feature: add draggable option for groups

### LINKED ISSUE #1692: Make layers in a group draggable
**Is your feature request related to a problem? Please describe.**
I suggest a group setting for making layers in the group draggable, meaning they can be rearranged inside that group to control their draw order. Perhaps most useful for layers added by the user.

### PR DESCRIPTION
**Pull request by jokd**
Fixes #1692 
Set `draggable: true` to make a group sortable by dragging layers. Useful for groups with user added layers.

### CODE REVIEW

**Comment by Grammostola** [comment]
Well done, I think I like the visual effect (lines move)  slightly more than layermanager's (visible dropzones) but honestly they're both pretty great. A (rearranged) layer (draw) order seems to apply to print and post-print. 
There's an error (that doesn't appear to hinder any bit of functionality) in the console when dragging a layer unto the legend area:
```console
group.js?e8dc:201 
        
       Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
    at HTMLLIElement.handleDragEnter (group.js?e8dc:201:1)
handleDragEnter @ group.js?e8dc:201
``` 
(that does not happen with the current master)

**Comment by jokd** [comment]
Should be fixed now (but drag and drop onto the legend have never worked, right?)

**Comment by Grammostola** [comment]
Seems fixed now (no crash when hovering over). Re ever worked to actually drop on the legend: don't know, isn't working in the current master anyway.

**Comment by jokd** [comment]
OK to merge?

**Comment by Grammostola** [comment]
Yes, I think so

**Pull request merged**
