### PR TITLE
Proposed additions to the guidelines

### PR DESCRIPTION
**Pull request by jokd**

### CODE REVIEW

**Comment by markus659** [comment]
Made some minor changes. Might be getting ready for merging soon?

**Comment by tonnyandersson** [comment]
Still contains references to ES5 (DEVELOPING.md - Language) and Browserify (DEVELOPING.md - JavaScript).

**Comment by markus659** [comment]
Fixed the references spotted by @tonnyandersson.

**Comment by jokd** [comment]
Do we still support Internet Explorer 10? I am unable to test.

**Comment by markus659** [comment]
I believe we do, don't think we have dropped support for it. I usually don't test against IE10 though.

**Comment by tonnyandersson** [comment]
Perhaps we should remove - or at least rewrite - all references to Jquery. Then we should merge this before making new updates.

**Comment by jokd** [comment]
@tonnyandersson Please have a look again

**Comment by daRasmussen** [comment]
LGTM

**Comment by tonnyandersson** [comment]
Yep, looks good.

**Pull request merged**
