### PR TITLE
Fix for baseUrl not effecting footer image and image style.

### LINKED ISSUE #954: baseUrl option doesn´t affect all resources
**Describe the bug**
When loading origo with baseUrl option not all resources are affected.
File path to footer image, and file path to image for image style ignores baseUrl option.

Footer image and image style seems to be relative to location of html file where Origo is loaded instead of baseUrl.

Icon styles, print logo and GeoJSON source works as expected. 

**Expected behavior**
Loading Origo in index.html
`var origo = Origo('index.json', { baseUrl: './origo/' });`

In index.json
Print logo src 
`"src": "img/png/bild.png",`
Footer image src
`"img": "origo/img/png/bild.png",`

As print logo and footer image is using the same resource, both are expected to use the same path.
As baseUrl is set to './origo/', Footer image should not need the 'origo/' part of the path in this example.

### PR DESCRIPTION
**Pull request by Flodkvist**
Fixes #954

Added support for use of baseurl option to also include path for
- footer image
- image layer style.

### CODE REVIEW

**Comment by Flodkvist** [comment]
My gut tells me there should be a more elegent solution to this problem but I had trouble finding it.

Also, my testing i based almost entirley on our configuration for gi.karlstad.se. So I´m not sure if these changes could have a negative effect on layertypes we´re not using.
Test map.
https://gi.karlstad.se/jnft/karlstadUppd/
Config.
http://gi.karlstad.se/jnft/karlstadUppd/origo/index.json

**Comment by tonnyandersson** [comment]
For consistency, please use template literals for concatenation instead of `+` in _src/controls/legend.js_.

**Comment by tonnyandersson** [comment]
@Flodkvist A [base tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) might be a more elegant solution.

Works if you add the lines below to the `onInit` function of origo.js. However, I had to use the full `https://gi.karlstad.se..../origo/` baseUrl since I don't have the same file structure as you. Perhaps it won't work with just `./origo`. Not saying you should update this PR just yet. I'm just putting it up for discussion.

```
const base = document.createElement('base');
base.href = defaultConfig.baseUrl;
document.getElementsByTagName('head')[0].appendChild(base);
```

Not sure if it's the _best_ solution, though. There might be consequences...

**Comment by Flodkvist** [comment]
That does look elegent.
I can give it a go and see what I run into.

**Comment by Flodkvist** [comment]
@tonnyandersson 
I tested using your example and commented out all use of baseUrl ( https://github.com/Flodkvist/origo/tree/html-base-element )
The build is in use on https://gi.karlstad.se/jnft/karlstadBaseElement/

Seems to work great, and would leave a cleaner core.

I´m not sure if there are any drawbacks in needing to use a "complete" URL.
Or if it would have any impact on situations where one uses custom javascript styles.

**Comment by tonnyandersson** [comment]
@Flodkvist You shouldn't have to use a "complete" URL. Relative URLs work just fine. But you would have to remove all existing mentions of `baseUrl` throughout the code to avoid double base URLs.

Not sure what's the better approach here. Personally, I like the idea of a "global" base URL that is automatically added to all URLs. That way you should never have to think about adding a base URL string when implementing new stuff. On the other hand, some may find it much easier to read and understand the code if base URLs are explicitly stated in the code.

Thoughts on this, anyone? @jokd, @daRasmussen, @johnnyblasta, @Grammostola, @hallstaelin

**Comment by Flodkvist** [comment]
@tonnyandersson  Yes, quite right. No problem using relative URL. 
https://github.com/Flodkvist/origo/tree/html-base-element is cleaned up if the collective finds the base tag solution preferable.

I prefer the base tag solution, using baseUrl as before led to a bug that might have been there a long time without being noticed. Using the base tag seems safer for the feature.
I dont know if its positive in the big picture, but less lines of code and less files feels good.

**Comment by jokd** [comment]
I vote for the base-tag

**Comment by tonnyandersson** [comment]
Issue fixed with PR #1162.

**Pull request closed without merging**
